const paths = {
    'EPL': {
        "name": "English Premier League",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 20,
        "table": "https://www.flashscore.co.uk/football/england/premier-league/standings/#/OEEq9Yvp/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/premier-league/fixtures/",
    },
    "Championship": {
        "name": "Championship",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/championship/standings/#/WvIi7C9d/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/championship/fixtures/",
    },
    "League One": {
        "name": "League One",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/league-one/standings/#/MkMfTgWF/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/league-one/fixtures/",
    },
    "League Two": {
        "name": "League Two",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/league-two/standings/#/hIUsMBOk/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/league-two/fixtures/",
    },
    "National League": {
        "name": "Vanarama National League",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/national-league/standings/#/pQ0KZAwq/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/national-league/fixtures/",
    },
    "Ligue 1": {
        "name": "Ligue 1",
        "sport": "Football",
        "country": "France",
        "numberOfTeams": 18,
        "table": "https://www.flashscore.co.uk/football/france/ligue-1/standings/#/j9QeTLPP/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/france/ligue-1/fixtures/",
    },
    "Ligue 2": {
        "name": "Ligue 2",
        "sport": "Football",
        "country": "France",
        "numberOfTeams": 18,
        "table": "https://www.flashscore.co.uk/football/france/ligue-2/standings/#/0STrMwIa/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/france/ligue-2/fixtures/",
    },
    "National": {
        "name": "National FFF",
        "sport": "Football",
        "country": "France",
        "numberOfTeams": 17,
        "table": "https://www.flashscore.co.uk/football/france/national/standings/#/U7LaIeHO/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/france/national/fixtures/",
    },
    "Bundesliga": {
        'name': "Bundesliga",
        'sport': "Football",
        'country': "Germany",
        "numberOfTeams": 18,
        'table': "https://www.flashscore.co.uk/football/germany/bundesliga/standings/#/8UYeqfiD/standings/overall/",
        'fixtures': "https://www.flashscore.co.uk/football/germany/bundesliga/fixtures/",
    },
    "Bundesliga 2": {
        'name': '2. Bundesliga',
        'sport': 'Football',
        'country': 'Germany',
        "numberOfTeams": 18,
        'table': 'https://www.flashscore.co.uk/football/germany/2-bundesliga/standings/#/McQM1y7s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/germany/2-bundesliga/fixtures/',
    },
    '3. Liga': {
        'name': '3. Liga',
        'sport': 'Football',
        'country': 'Germany',
        "numberOfTeams": 20,
        'table': 'https://www.flashscore.co.uk/football/germany/3-liga/#/U7onbg66/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/germany/3-liga/fixtures/',
    },
    'Serie A': {
        'name': 'Serie A',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-a/standings/#/6PWwAsA7/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-a/fixtures/',
    },
    'Serie B': {
        'name': 'Serie B',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-b/standings/#/jwYYXp2E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-b/fixtures/',
    },
    'Serie CA': {
        'name': 'Serie C Group A',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-c-group-a/standings/#/p4HJqOoK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-c-group-a/fixtures/',
    },
    'Serie CB': {
        'name': 'Serie C Group B',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-c-group-b/standings/#/Uygjv29s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-c-group-b/fixtures/',
    },
    'Serie CC': {
        'name': 'Serie C Group C',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-c-group-c/standings/#/6LU5xtvf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-c-group-c/fixtures/',
    },
    'Premiership': {
        'name': 'Premiership',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/scotland/premiership/standings/#/r9r0HS9r/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/premiership/fixtures/',
    },
    'SC Championship': {
        'name': 'SC Championship',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/scotland/championship/standings/#/xtu5Z14n/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/championship/fixtures/',
    },
    'SC League One': {
        'name': 'SC League One',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/scotland/league-one/standings/#/dtCpJFuT/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/league-one/fixtures/',
    },
    'SC League Two': {
        'name': 'SC League Two',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/scotland/league-two/standings/#/Cx4Bycec/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/league-two/fixtures/',
    },
    'LaLiga': {
        'name': 'LaLiga',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/spain/laliga/standings/#/vcm2MhGk/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/laliga/fixtures/',
    },
    'LaLiga2': {
        'name': 'LaLiga2',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 22,
        'table': 'https://www.flashscore.co.uk/football/spain/laliga2/standings/#/zPtBKWp2/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/laliga2/fixtures/',
    },
    'Primera RFEF 1': {
        'name': 'Primera RFEF Group 1',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/spain/primera-rfef-group-1/standings/#/W6WzKfZ2/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/primera-rfef-group-1/fixtures/',
    },
    'Primera RFEF 2': {
        'name': 'Primera RFEF Group 2',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/spain/segunda-rfef-group-2/standings/#/QXgmt21t/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/primera-rfef-group-2/fixtures/',
    },
    'Abissnet Superiore': {
        'name': 'Abissnet Superiore',
        'sport': 'Football',
        'country': 'Albania',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/albania/abissnet-superiore/standings/#/8ECkLGL5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/albania/abissnet-superiore/fixtures/',
    },
    'Primera Divisio': {
        'name': 'Primera Divisio',
        'sport': 'Football',
        'country': 'Andorra',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/andorra/primera-divisio/standings/#/O89LE3B5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/andorra/primera-divisio/fixtures/',
    },
    'AR Premier League': {
        'name': 'AR Premier League',
        'sport': 'Football',
        'country': 'Armenia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/armenia/premier-league/standings/#/SpCaRE0E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/armenia/premier-league/fixtures/',
    },
    'AU Bundesliga': {
        'name': 'AU Bundesliga',
        'sport': 'Football',
        'country': 'Austria',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/austria/bundesliga/standings/#/WYMxZqqg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/austria/bundesliga/fixtures/',
    },
    'AZ Premier League': {
        'name': 'AZ Premier League',
        'sport': 'Football',
        'country': 'Azerbaijan',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/azerbaijan/premier-league/standings/#/xUUBfNMH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/azerbaijan/premier-league/fixtures/',
    },
    'Vysshaya Liga': {
        'name': 'Vysshaya Liga',
        'sport': 'Football',
        'country': 'Belarus',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/belarus/vysshaya-liga/standings/#/WrCSPYgt/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/belarus/vysshaya-liga/fixtures/',
    },
    'Jupiler Pro League': {
        'name': 'Jupiler Pro League',
        'sport': 'Football',
        'country': 'Belgium',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/belgium/jupiler-pro-league/standings/#/WbIIL8v0/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/belgium/jupiler-pro-league/fixtures/',
    },
    'Challenger Pro League': {
        'name': 'Challenger Pro League',
        'sport': 'Football',
        'country': 'Belgium',
        'numberOfTeams': 17,
        'table': 'https://www.flashscore.co.uk/football/belgium/challenger-pro-league/standings/#/4lti9jCi/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/belgium/challenger-pro-league/fixtures/',
    },
    'WWIN Liga BiH': {
        'name': 'WWIN Liga BiH',
        'sport': 'Football',
        'country': 'Bosnia and Herzegovina',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/bosnia-herzegovina/wwin-liga-bih/standings/#/vwgEhNbJ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bosnia-herzegovina/wwin-liga-bih/fixtures/',
    },
    'efbet League': {
        'name': 'efbet League',
        'sport': 'Football',
        'country': 'Bulgaria',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/bulgaria/efbet-league/standings/#/ID1TwQHr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bulgaria/efbet-league/fixtures/',
    },
    'HNL': {
        'name': 'HNL',
        'sport': 'Football',
        'country': 'Croatia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/croatia/hnl/standings/#/nFfMOClK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/croatia/hnl/fixtures/',
    },
    'Cyprus League': {
        'name': 'Cyprus League',
        'sport': 'Football',
        'country': 'Cyprus',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/cyprus/cyprus-league/standings/#/63RzcQXj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cyprus/cyprus-league/fixtures/',
    },
    'Chance Liga': {
        'name': 'Chance Liga',
        'sport': 'Football',
        'country': 'Czech Republic',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/czech-republic/chance-liga/standings/#/tGIvI38l/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/czech-republic/chance-liga/fixtures/',
    },
    'Chance Narodni Liga': {
        'name': 'Chance Narodni Liga',
        'sport': 'Football',
        'country': 'Czech Republic',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/czech-republic/chnl/standings/#/AwXWHfE5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/czech-republic/chnl/fixtures/',
    },
    'Superliga': {
        'name': 'Superliga',
        'sport': 'Football',
        'country': 'Denmark',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/denmark/superliga/standings/#/d4toV4hf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/denmark/superliga/fixtures/',
    },
    'Crystalbet Erovnuli Liga': {
        'name': 'Crystalbet Erovnuli Liga',
        'sport': 'Football',
        'country': 'Georgia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/georgia/crystalbet-erovnuli-liga/standings/#/h6YjUBfe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/georgia/crystalbet-erovnuli-liga/fixtures/',
    },
    'Super League': {
        'name': 'Super League',
        'sport': 'Football',
        'country': 'Greece',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/greece/super-league/standings/#/YqOkq45l/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/greece/super-league/fixtures/',
    },
    'NB I.': {
        'name': 'NB I.',
        'sport': 'Football',
        'country': 'Hungary',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/hungary/nb-i/standings/#/MgCTUmzK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/hungary/nb-i/fixtures/',
    },
    'NB II.': {
        'name': 'NB II.',
        'sport': 'Football',
        'country': 'Hungary',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/hungary/nb-ii/standings/#/hx3aPRcs/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/hungary/nb-ii/fixtures/',
    },
    'Ligat ha\'Al': {
        'name': 'Ligat ha\'Al',
        'sport': 'Football',
        'country': 'Israel',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/israel/ligat-ha-al/standings/#/QLw5lq1D/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/israel/ligat-ha-al/fixtures/',
    },
    'BGL Ligue': {
        'name': 'BGL Ligue',
        'sport': 'Football',
        'country': 'Luxembourg',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/luxembourg/bgl-ligue/standings/#/Ymj33sDD/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/luxembourg/bgl-ligue/fixtures/',
    },
    'Prva Crnogorska Liga': {
        'name': 'Prva Crnogorska Liga',
        'sport': 'Football',
        'country': 'Montenegro',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/montenegro/prva-crnogorska-liga/standings/#/hbjLULCO/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/montenegro/prva-crnogorska-liga/fixtures/',
    },
    'Eredivisie': {
        'name': 'Eredivisie',
        'sport': 'Football',
        'country': 'Netherlands',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/netherlands/eredivisie/standings/#/dWKtjvdd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/netherlands/eredivisie/fixtures/',
    },
    'Eerste Divisie': {
        'name': 'Eerste Divisie',
        'sport': 'Football',
        'country': 'Netherlands',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/netherlands/eerste-divisie/standings/#/lfs1AamS/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/netherlands/eerste-divisie/fixtures/',
    },
    'NIFL Premiership': {
        'name': 'NIFL Premiership',
        'sport': 'Football',
        'country': 'Northern Ireland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/northern-ireland/nifl-premiership/standings/#/naztrDXQ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/northern-ireland/nifl-premiership/fixtures/',
    },
    '1.MFL': {
        'name': '1.MFL',
        'sport': 'Football',
        'country': 'North Macedonia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/north-macedonia/1-mfl/standings/#/rNmH2bUG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/north-macedonia/1-mfl/fixtures/',
    },
    'Eliteserien': {
        'name': 'Eliteserien',
        'sport': 'Football',
        'country': 'Norway',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/norway/eliteserien/standings/#/r3NUJK6F/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/norway/eliteserien/fixtures/',
    },
    'Ekstraklasa': {
        'name': 'Ekstraklasa',
        'sport': 'Football',
        'country': 'Poland',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/poland/ekstraklasa/standings/#/rgKvyuf4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/poland/ekstraklasa/fixtures/',
    },
    'PL Division 1': {
        'name': 'PL Division 1',
        'sport': 'Football',
        'country': 'Poland',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/poland/division-1/standings/#/ATgMQzHj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/poland/division-1/fixtures/',
    },
    'Liga Portugal': {
        'name': 'Liga Portugal',
        'sport': 'Football',
        'country': 'Portugal',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/portugal/liga-portugal/standings/#/IgF19YCc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/portugal/liga-portugal/fixtures/',
    },
    'Liga Portugal 2': {
        'name': 'Liga Portugal 2',
        'sport': 'Football',
        'country': 'Portugal',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/portugal/liga-portugal-2/standings/#/j7D97CsA/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/portugal/liga-portugal-2/fixtures/',
    },
    'RO Superliga': {
        'name': 'RO Superliga',
        'sport': 'Football',
        'country': 'Romania',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/romania/superliga/standings/#/02YI7tIj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/romania/superliga/fixtures/',
    },
    'RU Premier League': {
        'name': 'RU Premier League',
        'sport': 'Football',
        'country': 'Russia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/russia/premier-league/standings/#/0UC6tdRa/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/russia/premier-league/fixtures/',
    },
    'FNL': {
        'name': 'FNL',
        'sport': 'Football',
        'country': 'Russia',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/russia/fnl/standings/#/CAqspVXi/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/russia/fnl/fixtures/',
    },
    'Mozzart Bet Super Liga': {
        'name': 'Mozzart Bet Super Liga',
        'sport': 'Football',
        'country': 'Serbia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/serbia/mozzart-bet-super-liga/standings/#/WCsa8Gn4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/serbia/mozzart-bet-super-liga/fixtures/',
    },
    'Nike liga': {
        'name': 'Nike liga',
        'sport': 'Football',
        'country': 'Slovakia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/slovakia/nike-liga/standings/#/UctGaeNF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/slovakia/nike-liga/fixtures/',
    },
    'Prva liga': {
        'name': 'Prva liga',
        'sport': 'Football',
        'country': 'Slovenia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/slovenia/prva-liga/standings/#/UBHtOA4s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/slovenia/prva-liga/fixtures/',
    },
    'SU Super League': {
        'name': 'SU Super League',
        'sport': 'Football',
        'country': 'Switzerland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/switzerland/super-league/standings/#/AXcskDUh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/switzerland/super-league/fixtures/',
    },
    'Challenge League': {
        'name': 'Challenge League',
        'sport': 'Football',
        'country': 'Switzerland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/switzerland/challenge-league/standings/#/pSmAL67l/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/switzerland/challenge-league/fixtures/',
    },
    'Super Lig': {
        'name': 'Super Lig',
        'sport': 'Football',
        'country': 'Turkey',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/turkey/super-lig/standings/#/EVZfW0bc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/turkey/super-lig/fixtures/',
    },
    '1.Lig': {
        'name': '1.Lig',
        'sport': 'Football',
        'country': 'Turkey',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/turkey/1-lig/standings/#/jgd2GKdJ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/turkey/1-lig/fixtures/',
    },
    'UA Premier League': {
        'name': 'UA Premier League',
        'sport': 'Football',
        'country': 'Ukraine',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/ukraine/premier-league/standings/#/ldxRUZwe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/ukraine/premier-league/fixtures/',
    },
    'Cymru Premier': {
        'name': 'Cymru Premier',
        'sport': 'Football',
        'country': 'Wales',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/wales/cymru-premier/standings/#/fuKrWpAF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/wales/cymru-premier/fixtures/',
    },
    'AL Ligue 1': {
        'name': 'AL Ligue 1',
        'sport': 'Football',
        'country': 'Algeria',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/algeria/ligue-1/standings/#/Iylbph6E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/algeria/ligue-1/fixtures/',
    },
    'Girabola': {
        'name': 'Girabola',
        'sport': 'Football',
        'country': 'Angola',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/angola/girabola/standings/#/hYzpjRb3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/angola/girabola/fixtures/',
    },
    'ABFA Premier League': {
        'name': 'ABFA Premier League',
        'sport': 'Football',
        'country': 'Antigua and Barbuda',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/antigua-barbuda/abfa-premier-league/standings/#/tALXrzcf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/antigua-barbuda/abfa-premier-league/fixtures/',
    },
    'Division di Honor': {
        'name': 'Division di Honor',
        'sport': 'Football',
        'country': 'Aruba',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/aruba/division-di-honor/standings/#/UXdLzqqn/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/aruba/division-di-honor/fixtures/',
    },
    'A-League': {
        'name': 'A-League',
        'sport': 'Football',
        'country': 'Australia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/australia/a-league/standings/#/ADPCmMSi/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/australia/a-league/fixtures/',
    },
    'BH Premier League': {
        'name': 'BH Premier League',
        'sport': 'Football',
        'country': 'Bahrain',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/bahrain/premier-league/standings/#/2HZas7mf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bahrain/premier-league/fixtures/',
    },
    'BFL': {
        'name': 'BFL',
        'sport': 'Football',
        'country': 'Bangladesh',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/bangladesh/bfl/standings/#/xlLBeIP1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bangladesh/bfl/fixtures/',
    },
    'BB Premier League': {
        'name': 'BB Premier League',
        'sport': 'Football',
        'country': 'Barbados',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/barbados/premier-league/standings/#/n3QvMoUH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/barbados/premier-league/fixtures/',
    },
    'BN Ligue 1': {
        'name': 'BN Ligue 1',
        'sport': 'Football',
        'country': 'Benin',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/benin/ligue-1/standings/#/6Zg0OKmB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/benin/ligue-1/fixtures/',
    },
    'BD Premier League': {
        'name': 'BD Premier League',
        'sport': 'Football',
        'country': 'Bermuda',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/bermuda/premier-league/standings/#/hEGySgf3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bermuda/premier-league/fixtures/',
    },
    'Division Profesional': {
        'name': 'Division Profesional',
        'sport': 'Football',
        'country': 'Bolivia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/bolivia/division-profesional/standings/#/2LBZzj8b/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bolivia/division-profesional/fixtures/',
    },
    'BW Premier League': {
        'name': 'BW Premier League',
        'sport': 'Football',
        'country': 'Botswana',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/botswana/premier-league/standings/#/MX4zZMOp/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/botswana/premier-league/fixtures/',
    },
    'Serie A Betano': {
        'name': 'Serie A Betano',
        'sport': 'Football',
        'country': 'Brasil',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/brazil/serie-a-betano/standings/#/Yi0LvPEj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/brazil/serie-a-betano/fixtures/',
    },
    'Serie B Superbet': {
        'name': 'Serie B Superbet',
        'sport': 'Football',
        'country': 'Brasil',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/brazil/serie-b-superbet/standings/#/vF2C38ii/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/brazil/serie-b-superbet/fixtures/',
    },
    'Serie C': {
        'name': 'Serie C',
        'sport': 'Football',
        'country': 'Brasil',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/brazil/serie-c/standings/#/I51G2S6c/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/brazil/serie-c/fixtures/',
    },
    'BF Premier League': {
        'name': 'BF Premier League',
        'sport': 'Football',
        'country': 'Burkina Faso',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/burkina-faso/premier-league/standings/#/IgTYK5Cd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/burkina-faso/premier-league/fixtures/',
    },
    'Primus League': {
        'name': 'Primus League',
        'sport': 'Football',
        'country': 'Burundi',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/burundi/primus-league/standings/#/E5vTr943/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/burundi/primus-league/fixtures/',
    },
    'CPL': {
        'name': 'CPL',
        'sport': 'Football',
        'country': 'Cambodia',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/football/cambodia/cpl/standings/#/MPKtZ42j/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cambodia/cpl/fixtures/',
    },
    'Elite One': {
        'name': 'Elite One',
        'sport': 'Football',
        'country': 'Cameroon',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/cameroon/elite-one/standings/#/rJDZtHLd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cameroon/elite-one/fixtures/',
    },
    'Canadian Premier League': {
        'name': 'Canadian Premier League',
        'sport': 'Football',
        'country': 'Canada',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/football/canada/canadian-premier-league/standings/#/pWJUXCrq/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/canada/canadian-premier-league/fixtures/',
    },
    'Campeonato Nacional': {
        'name': 'Campeonato Nacional',
        'sport': 'Football',
        'country': 'Cape Verde',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/cape-verde/campeonato-nacional/standings/#/pKTIYqZg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cape-verde/campeonato-nacional/fixtures/',
    },
    'CH Premier Division': {
        'name': 'CH Premier Division',
        'sport': 'Football',
        'country': 'Chad',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/chad/premiere-division/standings/#/pU6ELQTg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/chad/premiere-division/fixtures/',
    },
    'Liga de Primera': {
        'name': 'Liga de Primera',
        'sport': 'Football',
        'country': 'Chile',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/chile/liga-de-primera/standings/#/8vt19m8m/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/chile/liga-de-primera/fixtures/',
    },
    'CH Super League': {
        'name': 'CH Super League',
        'sport': 'Football',
        'country': 'China',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/china/super-league/standings/#/YZlK9BuF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/china/super-league/fixtures/',
    },
    'Primera A': {
        'name': 'Primera A',
        'sport': 'Football',
        'country': 'Columbia',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/colombia/primera-a/standings/#/8MWz6dnl/standings/',
        'fixtures': 'https://www.flashscore.co.uk/football/colombia/primera-a/fixtures/',
    },
    'CG Ligue 1': {
        'name': 'CG Ligue 1',
        'sport': 'Football',
        'country': 'Congo',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/congo/ligue-1/standings/#/nwkV5fPH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/congo/ligue-1/fixtures/',
    },
    'CGDR Ligue 1': {
        'name': 'CGDR Ligue 1',
        'sport': 'Football',
        'country': 'Congo DR',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/congo-dr/ligue-1/standings/#/UyBrKd6E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/congo-dr/ligue-1/fixtures/',
    },
    'CR Primera Division': {
        'name': 'CR Primera Division',
        'sport': 'Football',
        'country': 'Costa Rica',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/costa-rica/primera-division/standings/#/WIEkYhg4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/costa-rica/primera-division/fixtures/',
    },
    'AIHL': {
        'name': 'AIHL',
        'sport': 'Ice Hockey',
        'country': 'Australia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/ice-hockey/australia/aihl/standings/#/xf46HYKU/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/australia/aihl/fixtures/',
    },
    'ICE Hockey League': {
        'name': 'ICE Hockey League',
        'sport': 'Ice Hockey',
        'country': 'Austria',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/ice-hockey/austria/ice-hockey-league/standings/#/4hW4JWHl/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/austria/ice-hockey-league/fixtures/',
    },
    'Extraleague': {
        'name': 'Extraleague',
        'sport': 'Ice Hockey',
        'country': 'Belarus',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/ice-hockey/belarus/extraleague/standings/#/ITwAIO1b/live-standings/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/belarus/extraleague/fixtures/',
    },
    'Extraliga': {
        'name': 'Extraliga',
        'sport': 'Ice Hockey',
        'country': 'Czech Republic',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/ice-hockey/czech-republic/extraliga/standings/#/K0tmQWEr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/czech-republic/extraliga/fixtures/',
    },
    'Metal Ligaen': {
        'name': 'Metal Ligaen',
        'sport': 'Ice Hockey',
        'country': 'Denmark',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/ice-hockey/denmark/metal-ligaen/standings/#/lAcXtgo9/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/denmark/metal-ligaen/fixtures/',
    },
    'Liiga': {
        'name': 'Liiga',
        'sport': 'Ice Hockey',
        'country': 'Finland',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/ice-hockey/finland/liiga/standings/#/SCI7qRwB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/finland/liiga/fixtures/',
    },
    'Mestis': {
        'name': 'Mestis',
        'sport': 'Ice Hockey',
        'country': 'Finland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/ice-hockey/finland/mestis/standings/#/C2HlbQh4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/finland/mestis/fixtures/',
    },
    'Ligue Magnus': {
        'name': 'Ligue Magnus',
        'sport': 'Ice Hockey',
        'country': 'France',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/ice-hockey/france/ligue-magnus/standings/#/EBaLvR4F/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/france/ligue-magnus/fixtures/',
    },
    'FR D1': {
        'name': 'D1',
        'sport': 'Ice Hockey',
        'country': 'France',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/ice-hockey/france/d1/standings/#/xIpapMte/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/france/d1/fixtures/',
    },
    'DEL': {
        'name': 'DEL',
        'sport': 'Ice Hockey',
        'country': 'Germany',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/ice-hockey/germany/del/standings/#/Ofnfw9ee/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/germany/del/fixtures/',
    },
    'DEL2': {
        'name': 'DEL2',
        'sport': 'Ice Hockey',
        'country': 'Germany',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/ice-hockey/germany/del2/standings/#/4SWz5off/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/germany/del2/fixtures/',
    },
    'Erste Liga': {
        'name': 'Erste Liga',
        'sport': 'Ice Hockey',
        'country': 'Hungary',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/ice-hockey/hungary/erste-liga/standings/#/OnvGZBCk/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/hungary/erste-liga/fixtures/',
    },
    'KZ Championship': {
        'name': 'Championship',
        'sport': 'Ice Hockey',
        'country': 'Kazakhstan',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/ice-hockey/kazakhstan/championship/standings/#/vVpVXRAE/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/kazakhstan/championship/fixtures/',
    },
    'Optibet Hokeja Liga': {
        'name': 'Optibet Hokeja Liga',
        'sport': 'Ice Hockey',
        'country': 'Latvia',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/ice-hockey/latvia/optibet-hokeja-liga/standings/#/0f2d5Xwe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/latvia/optibet-hokeja-liga/fixtures/',
    },
    'EHL': {
        'name': 'EHL',
        'sport': 'Ice Hockey',
        'country': 'Norway',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/ice-hockey/norway/ehl/standings/#/8j4rkU6t/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/norway/ehl/fixtures/',
    },
    'NO Division 1': {
        'name': 'Division 1',
        'sport': 'Ice Hockey',
        'country': 'Norway',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/ice-hockey/norway/division-1/standings/#/rDGOs45U/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/norway/division-1/fixtures/',
    },
    'Polish Hockey League': {
        'name': 'Polish Hockey League',
        'sport': 'Ice Hockey',
        'country': 'Poland',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/ice-hockey/poland/polish-hockey-league/standings/#/t8twSNJc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/poland/polish-hockey-league/fixtures/',
    },
    'VHL': {
        'name': 'VHL',
        'sport': 'Ice Hockey',
        'country': 'Russia',
        'numberOfTeams': 32,
        'table': 'https://www.flashscore.co.uk/ice-hockey/russia/vhl/standings/#/4WEnb5Nh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/russia/vhl/fixtures/',
    },
    'Tipsport liga': {
        'name': 'Tipsport liga',
        'sport': 'Ice Hockey',
        'country': 'Slovakia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/ice-hockey/slovakia/tipsport-liga/standings/#/Yehl8DsS/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/slovakia/tipsport-liga/fixtures/',
    },
    'SK 1. Liga': {
        'name': '1. Liga',
        'sport': 'Ice Hockey',
        'country': 'Slovakia',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/ice-hockey/slovakia/1-liga/standings/#/U1hNOYR8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/slovakia/1-liga/fixtures/',
    },
    'SHL': {
        'name': 'SHL',
        'sport': 'Ice Hockey',
        'country': 'Sweden',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/ice-hockey/sweden/shl/standings/#/CMVpiF7T/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/sweden/shl/fixtures/',
    },
    'HockeyAllsvenskan': {
        'name': 'HockeyAllsvenskan',
        'sport': 'Ice Hockey',
        'country': 'Sweden',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/ice-hockey/sweden/hockeyallsvenskan/standings/#/4rZ60hpp/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/sweden/hockeyallsvenskan/fixtures/',
    },
    'SWH National League': {
        'name': 'National League',
        'sport': 'Ice Hockey',
        'country': 'Switzerland',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/ice-hockey/switzerland/national-league/standings/#/YwJVrFRr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/switzerland/national-league/fixtures/',
    },
    'Swiss League': {
        'name': 'Swiss League',
        'sport': 'Ice Hockey',
        'country': 'Switzerland',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/ice-hockey/switzerland/swiss-league/standings/#/fcFk1EmR/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/switzerland/swiss-league/fixtures/',
    },
    'UK Elite League': {
        'name': 'Elite League',
        'sport': 'Ice Hockey',
        'country': 'United Kingdom',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/ice-hockey/united-kingdom/elite-league/standings/#/KW6txNAs/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/ice-hockey/united-kingdom/elite-league/fixtures/',
    },
    'ALB Superliga': {
        'name': 'Superliga',
        'sport': 'Basketball',
        'country': 'Albania',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/albania/superliga/standings/#/Ol3rfDME/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/albania/superliga/fixtures/',
    },
    'ARB Liga A': {
        'name': 'Liga A',
        'sport': 'Basketball',
        'country': 'Argentina',
        'numberOfTeams': 19,
        'table': 'https://www.flashscore.co.uk/basketball/argentina/liga-a/standings/#/SU9wo9q1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/argentina/liga-a/fixtures/',
    },
    'NBL': {
        'name': 'NBL',
        'sport': 'Basketball',
        'country': 'Australia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/australia/nbl/standings/#/0E28bGvm/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/australia/nbl/fixtures/',
    },
    'Libobasquet': {
        'name': 'Libobasquet',
        'sport': 'Basketball',
        'country': 'Bolivia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/basketball/bolivia/libobasquet/standings/#/YNzctjZh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/bolivia/libobasquet/fixtures/',
    },
    'Prvenstvo BiH': {
        'name': 'Prvenstvo BiH',
        'sport': 'Basketball',
        'country': 'Bosnia & Herzegovina',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/basketball/bosnia-herzegovina/prvenstvo-bih/standings/#/Mo4BESgo/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/bosnia-herzegovina/prvenstvo-bih/fixtures/',
    },
    'Prvenstvo BiH Women': {
        'name': 'Prvenstvo BiH Women',
        'sport': 'Basketball',
        'country': 'Bosnia & Herzegovina',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/bosnia-herzegovina/prvenstvo-bih-women/standings/#/0h1DUZeM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/bosnia-herzegovina/prvenstvo-bih-women/fixtures/',
    },
    'NBB': {
        'name': 'NBB',
        'sport': 'Basketball',
        'country': 'Brazil',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/basketball/brazil/nbb/standings/#/6RkSbx7U/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/brazil/nbb/fixtures/',
    },
    'LBF Women': {
        'name': 'LBF Women',
        'sport': 'Basketball',
        'country': 'Brazil',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/brazil/lbf-women/standings/#/dthyxr96/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/brazil/lbf-women/fixtures/',
    },
    'BG NBL': {
        'name': 'NBL',
        'sport': 'Basketball',
        'country': 'Bulgaria',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/bulgaria/nbl/standings/#/2TN1FlcS/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/bulgaria/nbl/fixtures/',
    },
    'CBA': {
        'name': 'CBA',
        'sport': 'Basketball',
        'country': 'China',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/basketball/china/cba/standings/#/bHG0VsCC/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/china/cba/fixtures/',
    },
    'CR Premijer liga': {
        'name': 'Premijer liga',
        'sport': 'Basketball',
        'country': 'Croatia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/croatia/premijer-liga/standings/#/SnZMLwzR/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/croatia/premijer-liga/fixtures/',
    },
    'CYB Division A': {
        'name': 'Division A',
        'sport': 'Basketball',
        'country': 'Cyprus',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/cyprus/division-a/standings/#/8KVZWTmn/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/cyprus/division-a/fixtures/',
    },
    'CZ NBL': {
        'name': 'NBL',
        'sport': 'Basketball',
        'country': 'Czech Republic',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/czech-republic/nbl/standings/#/dncPWMID/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/czech-republic/nbl/fixtures/',
    },
    'ZBL Women': {
        'name': 'ZBL Women',
        'sport': 'Basketball',
        'country': 'Czech Republic',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/czech-republic/zbl-women/standings/#/jDIepLJG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/czech-republic/zbl-women/fixtures/',
    },
    'Basketligaen': {
        'name': 'Basketligaen',
        'sport': 'Basketball',
        'country': 'Denmark',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/denmark/basketligaen/standings/#/GQQ0MLl5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/denmark/basketligaen/fixtures/',
    },
    'DR LNB': {
        'name': 'LNB',
        'sport': 'Basketball',
        'country': 'Dominican Republic',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/basketball/dominican-republic/lnb/standings/#/lEyNTT1k/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/dominican-republic/lnb/fixtures/',
    },
    'LNB': {
        'name': 'LNB',
        'sport': 'Basketball',
        'country': 'France',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/basketball/france/lnb/standings/#/z1xTahro/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/france/lnb/fixtures/',
    },
    'LFB Women': {
        'name': 'LFB Women',
        'sport': 'Basketball',
        'country': 'France',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/france/lfb-women/standings/#/tdjdQUtp/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/france/lfb-women/fixtures/',
    },
    'GEB Superleague': {
        'name': 'Superleague',
        'sport': 'Basketball',
        'country': 'Georgia',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/georgia/superleague/standings/#/EP0rxG6r/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/georgia/superleague/fixtures/',
    },
    'BBL': {
        'name': 'BBL',
        'sport': 'Basketball',
        'country': 'Germany',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/basketball/germany/bbl/standings/#/rXnrx7Ca/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/germany/bbl/fixtures/',
    },
    'DBBL Women': {
        'name': 'DBBL Women',
        'sport': 'Basketball',
        'country': 'Germany',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/germany/dbbl-women/standings/#/vaKHD0PG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/germany/dbbl-women/fixtures/',
    },
    'Basket League': {
        'name': 'Basket League',
        'sport': 'Basketball',
        'country': 'Greece',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/basketball/greece/basket-league/standings/#/694d6IHj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/greece/basket-league/fixtures/',
    },
    'A1 Women': {
        'name': 'A1 Women',
        'sport': 'Basketball',
        'country': 'Greece',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/greece/a1-women/standings/#/408TujaK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/greece/a1-women/fixtures/',
    },
    'A1': {
        'name': 'A1',
        'sport': 'Basketball',
        'country': 'Hong Kong',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/hong-kong/a1/standings/#/Ctzg24Kr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/hong-kong/a1/fixtures/',
    },
    'NB I. A': {
        'name': 'NB I. A',
        'sport': 'Basketball',
        'country': 'Hungary',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/basketball/hungary/nb-i-a/standings/#/YFQwM3uo/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/hungary/nb-i-a/fixtures/',
    },
    'NB I. A Women': {
        'name': 'NB I. A Women',
        'sport': 'Basketball',
        'country': 'Hungary',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/hungary/nb-i-a-women/standings/#/rugyh2GM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/hungary/nb-i-a-women/fixtures/',
    },
    'ICB Premier League': {
        'name': 'Premier League',
        'sport': 'Basketball',
        'country': 'Iceland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/iceland/premier-league/standings/#/jyTblgFl/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/iceland/premier-league/fixtures/',
    },
    'IBL': {
        'name': 'IBL',
        'sport': 'Basketball',
        'country': 'Indonesia',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/indonesia/ibl/standings/#/byoa50HP/standings/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/indonesia/ibl/fixtures/',
    },
    'IRB Super League': {
        'name': 'Super League',
        'sport': 'Basketball',
        'country': 'Iran',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/iran/super-league/standings/#/CMZuedvC/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/iran/super-league/fixtures/',
    },
    'IRB SuperLeague': {
        'name': 'SuperLeague',
        'sport': 'Basketball',
        'country': 'Ireland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/ireland/superleague/standings/#/raZn6DhU/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/ireland/superleague/fixtures/',
    },
    'ISB Super League': {
        'name': 'Super League',
        'sport': 'Basketball',
        'country': 'Israel',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/basketball/israel/super-league/standings/#/bw4B24id/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/israel/super-league/fixtures/',
    },
    'WBL Women': {
        'name': 'WBL Women',
        'sport': 'Basketball',
        'country': 'Israel',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/israel/wbl-women/standings/#/IuQkm2sR/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/israel/wbl-women/fixtures/',
    },
    'Lega A': {
        'name': 'Lega A',
        'sport': 'Basketball',
        'country': 'Italy',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/basketball/italy/lega-a/standings/#/f11X1K56/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/italy/lega-a/fixtures/',
    },
    'Serie A1 Women': {
        'name': 'Serie A1 Women',
        'sport': 'Basketball',
        'country': 'Italy',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/italy/serie-a1-women/standings/#/8QzdrdJb/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/italy/serie-a1-women/fixtures/',
    },
    'W League Women': {
        'name': 'W League Women',
        'sport': 'Basketball',
        'country': 'Japan',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/basketball/japan/w-league-women/standings/#/8099EKaf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/japan/w-league-women/fixtures/',
    },
    'JOB Premier League': {
        'name': 'Premier League',
        'sport': 'Basketball',
        'country': 'Jordan',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/basketball/jordan/premier-league/standings/#/S6gDjcUs/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/jordan/premier-league/fixtures/',
    },
    'KSB Superliga': {
        'name': 'Superliga',
        'sport': 'Basketball',
        'country': 'Kosovo',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/basketball/kosovo/superliga/standings/#/n7voAcGG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/kosovo/superliga/fixtures/',
    },
    'LBB Division 1': {
        'name': 'Division 1',
        'sport': 'Basketball',
        'country': 'Lebanon',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/lebanon/division-1/standings/#/fHXsHzBm/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/lebanon/division-1/fixtures/',
    },
    'LKL': {
        'name': 'LKL',
        'sport': 'Basketball',
        'country': 'Lithuania',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/basketball/lithuania/lkl/standings/#/xd9AEZdc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/lithuania/lkl/fixtures/',
    },
    'LBBL': {
        'name': 'LBBL',
        'sport': 'Basketball',
        'country': 'Luxembourg',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/luxembourg/lbbl/standings/#/l0C6achn/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/luxembourg/lbbl/fixtures/',
    },
    'LNBP': {
        'name': 'LNBP',
        'sport': 'Basketball',
        'country': 'Mexico',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/basketball/mexico/lnbp/standings/#/Sx2nfJdM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/mexico/lnbp/fixtures/',
    },
    'Prva A Liga': {
        'name': 'Prva A Liga',
        'sport': 'Basketball',
        'country': 'Montenegro',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/basketball/montenegro/prva-a-liga/standings/#/jN3uLqZ7/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/montenegro/prva-a-liga/fixtures/',
    },
    'NEB WBL Women': {
        'name': 'WBL Women',
        'sport': 'Basketball',
        'country': 'Netherlands',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/netherlands/wbl-women/standings/#/Kv7WZtcU/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/netherlands/wbl-women/fixtures/',
    },
    'NZB NBL': {
        'name': 'NBL',
        'sport': 'Basketball',
        'country': 'New Zealand',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/new-zealand/nbl/standings/#/KSxUhyl3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/new-zealand/nbl/fixtures/',
    },
    'NMB Super League': {
        'name': 'Super League',
        'sport': 'Basketball',
        'country': 'North Macedonia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/north-macedonia/super-league/standings/#/vc9InsvH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/north-macedonia/super-league/fixtures/',
    },
    'BLNO': {
        'name': 'BLNO',
        'sport': 'Basketball',
        'country': 'Norway',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/norway/blno/standings/#/W62YGVoR/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/norway/blno/fixtures/',
    },
    'Basket Liga': {
        'name': 'Basket Liga',
        'sport': 'Basketball',
        'country': 'Poland',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/basketball/poland/basket-liga/standings/#/j90aEmDd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/poland/basket-liga/fixtures/',
    },
    'Basket Liga Women': {
        'name': 'Basket Liga Women',
        'sport': 'Basketball',
        'country': 'Poland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/poland/basket-liga-women/standings/#/6PbHQoEa/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/poland/basket-liga-women/fixtures/',
    },
    'LPB': {
        'name': 'LPB',
        'sport': 'Basketball',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/portugal/lpb/standings/#/zeZYAidM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/portugal/lpb/fixtures/',
    },
    'PRB LFB Women': {
        'name': 'LFB Women',
        'sport': 'Basketball',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/portugal/lfb-women/standings/#/Ye81t31D/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/portugal/lfb-women/fixtures/',
    },
    'QBL': {
        'name': 'QBL',
        'sport': 'Basketball',
        'country': 'Qatar',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/basketball/qatar/qbl/standings/#/06lYywE4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/qatar/qbl/fixtures/',
    },
    'Liga National Women': {
        'name': 'Liga National Women',
        'sport': 'Basketball',
        'country': 'Romania',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/basketball/romania/liga-national-women/standings/#/llMAmxs1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/romania/liga-national-women/fixtures/',
    },
    'VTB United League': {
        'name': 'VTB United League',
        'sport': 'Basketball',
        'country': 'Russia',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/russia/vtb-united-league/standings/#/zPOqkOQ1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/russia/vtb-united-league/fixtures/',
    },
    'Premier League Women': {
        'name': 'Premier League Women',
        'sport': 'Basketball',
        'country': 'Russia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/basketball/russia/premier-league-women/standings/#/h4XKDVaU/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/russia/premier-league-women/fixtures/',
    },
    'SAB Premier League': {
        'name': 'Premier League',
        'sport': 'Basketball',
        'country': 'Saudi Arabia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/saudi-arabia/premier-league/standings/#/rDU5d6YR/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/saudi-arabia/premier-league/fixtures/',
    },
    'SPB NBL': {
        'name': 'NBL',
        'sport': 'Basketball',
        'country': 'Singapore',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/singapore/nbl/standings/#/dh6RpU2C/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/singapore/nbl/fixtures/',
    },
    'SKB Extraliga': {
        'name': 'Extraliga',
        'sport': 'Basketball',
        'country': 'Slovakia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/slovakia/extraliga/standings/#/vFQsMDZ0/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/slovakia/extraliga/fixtures/',
    },
    'Extraliga Women': {
        'name': 'Extraliga Women',
        'sport': 'Basketball',
        'country': 'Slovakia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/slovakia/extraliga-women/standings/#/0hwYzDlf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/slovakia/extraliga-women/fixtures/',
    },
    'Liga OTP banka': {
        'name': 'Liga OTP banka',
        'sport': 'Basketball',
        'country': 'Slovenia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/slovenia/liga-otp-banka/standings/#/dGKKE5MG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/slovenia/liga-otp-banka/fixtures/',
    },
    'KBL': {
        'name': 'KBL',
        'sport': 'Basketball',
        'country': 'South Korea',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/south-korea/kbl/standings/#/n74cYfDT/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/south-korea/kbl/fixtures/',
    },
    'ACB': {
        'name': 'ACB',
        'sport': 'Basketball',
        'country': 'Spain',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/basketball/spain/acb/standings/#/CSSYsnUs/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/spain/acb/fixtures/',
    },
    'Liga Femenina Women': {
        'name': 'Liga Femenina Women',
        'sport': 'Basketball',
        'country': 'Spain',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/basketball/spain/liga-femenina-women/standings/#/hMtTiBOh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/spain/liga-femenina-women/fixtures/',
    },
    'Basketligan': {
        'name': 'Basketligan',
        'sport': 'Basketball',
        'country': 'Sweden',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/sweden/basketligan/standings/#/OEOmYeGM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/sweden/basketligan/fixtures/',
    },
    'Basketligan Women': {
        'name': 'Basketligan Women',
        'sport': 'Basketball',
        'country': 'Sweden',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/basketball/sweden/basketligan-women/standings/#/MFa6xih2/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/sweden/basketligan-women/fixtures/',
    },
    'SB League': {
        'name': 'SB League',
        'sport': 'Basketball',
        'country': 'Switzerland',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/basketball/switzerland/sb-league/standings/#/CbsW0cuo/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/switzerland/sb-league/fixtures/',
    },
    'SB League Women': {
        'name': 'SB League Women',
        'sport': 'Basketball',
        'country': 'Switzerland',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/basketball/switzerland/sb-league-women/standings/#/GQdbJd1T/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/switzerland/sb-league-women/fixtures/',
    },
    'TKB Super Lig': {
        'name': 'Super Lig',
        'sport': 'Basketball',
        'country': 'Turkey',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/basketball/turkey/super-lig/standings/#/ni4GXRSE/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/turkey/super-lig/fixtures/',
    },
    'KBSL Women': {
        'name': 'KBSL Women',
        'sport': 'Basketball',
        'country': 'Turkey',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/basketball/turkey/kbsl-women/standings/#/6asV6AQp/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/turkey/kbsl-women/fixtures/',
    },
    'FBU Superleague': {
        'name': 'FBU Superleague',
        'sport': 'Basketball',
        'country': 'Ukraine',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/ukraine/fbu-superleague/standings/#/rwrK7Ba3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/ukraine/fbu-superleague/fixtures/',
    },
    'SLB': {
        'name': 'SLB',
        'sport': 'Basketball',
        'country': 'United Kingdom',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/basketball/united-kingdom/slb/standings/#/MeFNzILs/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/united-kingdom/slb/fixtures/',
    },
    'SLB Women': {
        'name': 'SLB Women',
        'sport': 'Basketball',
        'country': 'United Kingdom',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/basketball/united-kingdom/slb-women/standings/#/6eLOpZZa/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/basketball/united-kingdom/slb-women/fixtures/',
    },
    'Liga Women': {
        'name': 'Liga Women',
        'sport': 'Volleyball',
        'country': 'Argentina',
        'numberOfTeams': 15,
        'table': 'https://www.flashscore.co.uk/volleyball/argentina/liga-women/standings/#/xlBMu8Am/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/argentina/liga-women/fixtures/',
    },
    'AVL': {
        'name': 'AVL',
        'sport': 'Volleyball',
        'country': 'Austria',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/austria/avl/standings/#/p4DzSTB4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/austria/avl/fixtures/',
    },
    'Division A': {
        'name': 'Division A',
        'sport': 'Volleyball',
        'country': 'Belarus',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/belarus/division-a/standings/#/KMmCsYAc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belarus/division-a/fixtures/',
    },
    'Championship Women': {
        'name': 'Championship Women',
        'sport': 'Volleyball',
        'country': 'Belarus',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/belarus/championship-women/standings/#/rDKdby7C/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belarus/championship-women/fixtures/',
    },
    'Volley League': {
        'name': 'Volley League',
        'sport': 'Volleyball',
        'country': 'Belgium',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league/standings/#/ATVv7dW0/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league/fixtures/',
    },
    'Volley League Women': {
        'name': 'Volley League Women',
        'sport': 'Volleyball',
        'country': 'Belgium',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league-women/standings/#/dET3kS7r/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league-women/fixtures/',
    },
    'Premijer liga': {
        'name': 'Premijer liga',
        'sport': 'Volleyball',
        'country': 'Bosnia & Herzegovina',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/bosnia-herzegovina/premijer-liga/standings/#/8AE7aIgc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/bosnia-herzegovina/premijer-liga/fixtures/',
    },
    'SuperLiga BRV': {
        'name': 'SuperLiga',
        'sport': 'Volleyball',
        'country': 'Brazil',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/brazil/superliga/standings/#/vs3g3i0k/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/brazil/superliga/fixtures/',
    },
    'Superliga - Women BRV': {
        'name': 'Superliga - Women',
        'sport': 'Volleyball',
        'country': 'Brazil',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/brazil/superliga-women/standings/#/SzBqIjFr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/brazil/superliga-women/fixtures/',
    },
    'SuperLiga BGV': {
        'name': 'SuperLiga',
        'sport': 'Volleyball',
        'country': 'Bulgaria',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga/standings/#/fqERiF2T/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga/fixtures/',
    },
    'Superliga - Women BGV': {
        'name': 'Superliga - Women',
        'sport': 'Volleyball',
        'country': 'Bulgaria',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga-women/standings/#/EZicDjtm/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga/fixtures/',
    },
    'Superliga CRV': {
        'name': 'Superliga',
        'sport': 'Volleyball',
        'country': 'Croatia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/croatia/superliga/standings/#/SOGtAwfB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/croatia/superliga/fixtures/',
    },
    'Superliga Women CRV': {
        'name': 'Superliga Women',
        'sport': 'Volleyball',
        'country': 'Croatia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/croatia/superliga-women/standings/#/ImQBFPy8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/croatia/superliga-women/fixtures/',
    },
    'Extraliga CZEV': {
        'name': 'Extraliga',
        'sport': 'Volleyball',
        'country': 'Czech Republic',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga/standings/#/reiEGDcK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga/fixtures/',
    },
    'Extraliga Women CZEV': {
        'name': 'Extraliga Women',
        'sport': 'Volleyball',
        'country': 'Czech Republic',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga-women/standings/#/8jnI5mkJ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga-women/fixtures/',
    },
    'Volleyligaen': {
        'name': 'Volleyligaen',
        'sport': 'Volleyball',
        'country': 'Denmark',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen/standings/#/zXUcuk7T/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen/fixtures/',
    },
    'Volleyligaen Women': {
        'name': 'Volleyligaen Women',
        'sport': 'Volleyball',
        'country': 'Denmark',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen-women/standings/#/2wqzNa3F/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen-women/fixtures/',
    },
    'Super League ENGV': {
        'name': 'Super League',
        'sport': 'Volleyball',
        'country': 'England',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/england/super-league/standings/#/dMgYfg9s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/england/super-league/fixtures/',
    },
    'Super League Women': {
        'name': 'Super League Women',
        'sport': 'Volleyball',
        'country': 'England',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/england/super-league-women/standings/#/6yZm4ubT/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/england/super-league-women/fixtures/',
    },
    'Meistriliiga Women': {
        'name': 'Meistriliiga Women',
        'sport': 'Volleyball',
        'country': 'Estonia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/estonia/meistriliiga-women/standings/#/W8yGbIVb/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/estonia/meistriliiga-women/fixtures/',
    },
    'Mestaruusliiga': {
        'name': 'Mestaruusliiga',
        'sport': 'Volleyball',
        'country': 'Finland',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga/standings/#/QPLQ6DET/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga/fixtures/',
    },
    'Mestaruusliiga Women': {
        'name': 'Mestaruusliiga Women',
        'sport': 'Volleyball',
        'country': 'Finland',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga-women/standings/#/xWom5a46/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga-women/fixtures/',
    },
    'Ligue A': {
        'name': 'Ligue A',
        'sport': 'Volleyball',
        'country': 'France',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/france/ligue-a/standings/#/WzjcpSNF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/france/ligue-a/fixtures/',
    },
    'Ligue A Women': {
        'name': 'Ligue A Women',
        'sport': 'Volleyball',
        'country': 'France',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/volleyball/france/ligue-a-women/standings/#/dj77DxFG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/france/ligue-a-women/fixtures/',
    },
    '1. Bundesliga': {
        'name': '1. Bundesliga',
        'sport': 'Volleyball',
        'country': 'Germany',
        'numberOfTeams': 15,
        'table': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga/standings/#/4xxUGybK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga/fixtures/',
    },
    '1. Bundesliga Women': {
        'name': '1. Bundesliga Women',
        'sport': 'Volleyball',
        'country': 'Germany',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga-women/standings/#/4KlnFuYj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga-women/fixtures/',
    },
    'A1 GREV': {
        'name': 'A1',
        'sport': 'Volleyball',
        'country': 'Greece',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/greece/a1/standings/#/2Zh74n2n/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/greece/a1/fixtures/',
    },
    'A1 Women GREV': {
        'name': 'A1 Women',
        'sport': 'Volleyball',
        'country': 'Greece',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/greece/a1-women/standings/#/Ia4zHp3k/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/greece/a1-women/fixtures/',
    },
    'Extraliga HUV': {
        'name': 'Extraliga',
        'sport': 'Volleyball',
        'country': 'Hungary',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga/standings/#/x6A4QiQh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga/fixtures/',
    },
    'Extraliga Women HUV': {
        'name': 'Extraliga Women',
        'sport': 'Volleyball',
        'country': 'Hungary',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga-women/standings/#/0pBq578c/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga-women/fixtures/',
    },
    'Mizunodeild': {
        'name': 'Mizunodeild',
        'sport': 'Volleyball',
        'country': 'Iceland',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/iceland/mizunodeild/standings/#/CIRSZNc3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/iceland/mizunodeild/fixtures/',
    },
    'Prime Volleyball': {
        'name': 'Prime Volleyball',
        'sport': 'Volleyball',
        'country': 'India',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/india/prime-volleyball/standings/#/4YN1VJgo/standings/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/india/prime-volleyball/fixtures/',
    },
    'Super League IRNV': {
        'name': 'Super League',
        'sport': 'Volleyball',
        'country': 'Iran',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/iran/super-league/standings/#/f3IwLXxg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/iran/super-league/fixtures/',
    },
    'Premier League ISRV': {
        'name': 'Premier League',
        'sport': 'Volleyball',
        'country': 'Israel',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/israel/premier-league/standings/#/KSzZNlqK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/israel/premier-league/fixtures/',
    },
    'SuperLega': {
        'name': 'SuperLega',
        'sport': 'Volleyball',
        'country': 'Italy',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/italy/superlega/standings/#/CMyd5b1D/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/italy/superlega/fixtures/',
    },
    'Serie A1 Women ITAV': {
        'name': 'Serie A1 Women',
        'sport': 'Volleyball',
        'country': 'Italy',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/italy/serie-a1-women/standings/#/lIDDcDbB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/italy/serie-a1-women/fixtures/',
    },
    'SV.League': {
        'name': 'SV.League',
        'sport': 'Volleyball',
        'country': 'Japan',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/japan/sv-league/standings/#/GEYn8FZp/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/japan/sv-league/fixtures/',
    },
    'SV.League Women': {
        'name': 'SV.League Women',
        'sport': 'Volleyball',
        'country': 'Japan',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/japan/sv-league-women/standings/#/nRncuEAM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/japan/sv-league-women/fixtures/',
    },
    'National League KAZV': {
        'name': 'National League',
        'sport': 'Volleyball',
        'country': 'Kazakhstan',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league/standings/#/fPLyMNGG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league/fixtures/',
    },
    'National League Women': {
        'name': 'National League Women',
        'sport': 'Volleyball',
        'country': 'Kazakhstan',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league-women/standings/#/fVQaGhpe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league-women/fixtures/',
    },
    '1st Division': {
        'name': '1st Division',
        'sport': 'Volleyball',
        'country': 'Lebanon',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/lebanon/1st-division/standings/#/hvC6nHQj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/lebanon/1st-division/fixtures/',
    },
    'Superliga Women MNTV': {
        'name': 'Superliga Women',
        'sport': 'Volleyball',
        'country': 'Montenegro',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/montenegro/superliga-women/standings/#/SxnWFGhd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/montenegro/superliga-women/fixtures/',
    },
    'Eredivisie NETV': {
        'name': 'Eredivisie',
        'sport': 'Volleyball',
        'country': 'Netherlands',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie/standings/#/Kt8MdPYQ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie/fixtures/',
    },
    'Eredivisie Women': {
        'name': 'Eredivisie Women',
        'sport': 'Volleyball',
        'country': 'Netherlands',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie-women/standings/#/6mgN4gHb/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie-women/fixtures/',
    },
    'Eliteserien NORV': {
        'name': 'Eliteserien',
        'sport': 'Volleyball',
        'country': 'Norway',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien/standings/#/Oj0KU9pA/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien/fixtures/',
    },
    'Eliteserien Women': {
        'name': 'Eliteserien Women',
        'sport': 'Volleyball',
        'country': 'Norway',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien-women/standings/#/UwQ7LdDD/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien-women/fixtures/',
    },
    'LNSV': {
        'name': 'LNSV',
        'sport': 'Volleyball',
        'country': 'Peru',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/peru/lnsv/standings/#/8IAmewkQ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/peru/lnsv/fixtures/',
    },
    'LNSV Women': {
        'name': 'LNSV Women',
        'sport': 'Volleyball',
        'country': 'Peru',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/peru/lnsv-women/standings/#/MLEvqLMH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/peru/lnsv-women/fixtures/',
    },
    'PlusLiga': {
        'name': 'PlusLiga',
        'sport': 'Volleyball',
        'country': 'Poland',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/poland/plusliga/standings/#/zD2V5lKr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/poland/plusliga/fixtures/',
    },
    'TAURON Liga Women': {
        'name': 'TAURON Liga Women',
        'sport': 'Volleyball',
        'country': 'Poland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/poland/tauron-liga-women/standings/#/IqOgnHwh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/poland/tauron-liga-women/fixtures/',
    },
    'Campeonato Nacional PORV': {
        'name': 'Campeonato Nacional',
        'sport': 'Volleyball',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/portugal/campeonato-nacional/standings/#/WWcvOKJP/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/portugal/campeonato-nacional/fixtures/',
    },
    '1. Divisao Women': {
        'name': '1. Divisao Women',
        'sport': 'Volleyball',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/portugal/1-divisao-women/standings/#/zsjxd5V8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/portugal/1-divisao-women/fixtures/',
    },
    'Volleyball League': {
        'name': 'Volleyball League',
        'sport': 'Volleyball',
        'country': 'Qatar',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/qatar/volleyball-league/standings/#/lARRDSXo/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/qatar/volleyball-league/fixtures/',
    },
    'Divizia A1': {
        'name': 'Divizia A1',
        'sport': 'Volleyball',
        'country': 'Romania',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1/standings/#/CfZPZRwC/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1/fixtures/',
    },
    'Divizia A1 Women': {
        'name': 'Divizia A1 Women',
        'sport': 'Volleyball',
        'country': 'Romania',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1-women/standings/#/IRGbjvU9/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1-women/fixtures/',
    },
    'Super League RUSV': {
        'name': 'Super League',
        'sport': 'Volleyball',
        'country': 'Russia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/volleyball/russia/super-league/standings/#/fRflGfcL/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/russia/super-league/fixtures/',
    },
    'Super League - Women RUSV': {
        'name': 'Super League - Women',
        'sport': 'Volleyball',
        'country': 'Russia',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/russia/super-league-women/standings/#/88irGk05/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/russia/super-league-women/fixtures/',
    },
    'Superliga SRBV': {
        'name': 'Superliga',
        'sport': 'Volleyball',
        'country': 'Serbia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/serbia/superliga/standings/#/f3jJ5jX8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/serbia/superliga/fixtures/',
    },
    'Superliga Women SRBV': {
        'name': 'Superliga Women',
        'sport': 'Volleyball',
        'country': 'Serbia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/serbia/superliga-women/standings/#/E7iqAxF5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/serbia/superliga-women/fixtures/',
    },
    'Extraliga SVKV': {
        'name': 'Extraliga',
        'sport': 'Volleyball',
        'country': 'Slovakia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga/standings/#/6uF0pzwg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga/fixtures/',
    },
    'Extraliga Women SVKV': {
        'name': 'Extraliga Women',
        'sport': 'Volleyball',
        'country': 'Slovakia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga-women/standings/#/2w1O3LZr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga-women/fixtures/',
    },
    '1. DOL': {
        'name': '1. DOL',
        'sport': 'Volleyball',
        'country': 'Slovenia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/slovenia/1-dol/standings/#/zmTR92TI/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/slovenia/1-dol/fixtures/',
    },
    'SuperLiga SPAV': {
        'name': 'SuperLiga',
        'sport': 'Volleyball',
        'country': 'Spain',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/spain/superliga/standings/#/WAbtzgrH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/spain/superliga/fixtures/',
    },
    'Elitserien': {
        'name': 'Elitserien',
        'sport': 'Volleyball',
        'country': 'Sweden',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien/standings/#/SrklaUSP/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien/fixtures/',
    },
    'Elitserien Women': {
        'name': 'Elitserien Women',
        'sport': 'Volleyball',
        'country': 'Sweden',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien-women/standings/#/QwoE3GAM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien-women/fixtures/',
    },
    'NLA': {
        'name': 'NLA',
        'sport': 'Volleyball',
        'country': 'Switzerland',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/switzerland/nla/standings/#/65KZNA1e/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/switzerland/nla/fixtures/',
    },
    'NLA Women': {
        'name': 'NLA Women',
        'sport': 'Volleyball',
        'country': 'Switzerland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/switzerland/nla-women/standings/#/WCZSXILU/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/switzerland/nla-women/fixtures/',
    },
    'Efeler Ligi': {
        'name': 'Efeler Ligi',
        'sport': 'Volleyball',
        'country': 'Turkey',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/turkey/efeler-ligi/standings/#/K82wvr9j/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/turkey/efeler-ligi/fixtures/',
    },
    'Sultanlar Ligi Women': {
        'name': 'Sultanlar Ligi Women',
        'sport': 'Volleyball',
        'country': 'Turkey',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/turkey/sultanlar-ligi-women/standings/#/2Hab6Xrf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/turkey/sultanlar-ligi-women/fixtures/',
    },
    'Superleague UKRV': {
        'name': 'Superleague',
        'sport': 'Volleyball',
        'country': 'Ukraine',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/ukraine/superleague/standings/#/23OXsI1S/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/ukraine/superleague/fixtures/',
    },

}

module.exports = paths;