const paths = {
    'EPL': {
        "name": "English Premier League",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 20,
        "table": "https://www.flashscore.co.uk/football/england/premier-league/standings/#/OEEq9Yvp/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/premier-league/fixtures/",
    },
    "Championship": {
        "name": "Championship",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/championship/standings/#/WvIi7C9d/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/championship/fixtures/",
    },
    "League One": {
        "name": "League One",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/league-one/standings/#/MkMfTgWF/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/league-one/fixtures/",
    },
    "League Two": {
        "name": "League Two",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/league-two/standings/#/hIUsMBOk/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/league-two/fixtures/",
    },
    "National League": {
        "name": "Vanarama National League",
        "sport": "Football",
        "country": "England",
        "numberOfTeams": 24,
        "table": "https://www.flashscore.co.uk/football/england/national-league/standings/#/pQ0KZAwq/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/england/national-league/fixtures/",
    },
    "Ligue 1": {
        "name": "Ligue 1",
        "sport": "Football",
        "country": "France",
        "numberOfTeams": 18,
        "table": "https://www.flashscore.co.uk/football/france/ligue-1/standings/#/j9QeTLPP/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/france/ligue-1/fixtures/",
    },
    "Ligue 2": {
        "name": "Ligue 2",
        "sport": "Football",
        "country": "France",
        "numberOfTeams": 18,
        "table": "https://www.flashscore.co.uk/football/france/ligue-2/standings/#/0STrMwIa/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/france/ligue-2/fixtures/",
    },
    "National": {
        "name": "National FFF",
        "sport": "Football",
        "country": "France",
        "numberOfTeams": 17,
        "table": "https://www.flashscore.co.uk/football/france/national/standings/#/U7LaIeHO/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/football/france/national/fixtures/",
    },
    "Bundesliga": {
        'name': "Bundesliga",
        'sport': "Football",
        'country': "Germany",
        "numberOfTeams": 18,
        'table': "https://www.flashscore.co.uk/football/germany/bundesliga/standings/#/8UYeqfiD/standings/overall/",
        'fixtures': "https://www.flashscore.co.uk/football/germany/bundesliga/fixtures/",
    },
    "Bundesliga 2": {
        'name': '2. Bundesliga',
        'sport': 'Football',
        'country': 'Germany',
        "numberOfTeams": 18,
        'table': 'https://www.flashscore.co.uk/football/germany/2-bundesliga/standings/#/McQM1y7s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/germany/2-bundesliga/fixtures/',
    },
    '3. Liga': {
        'name': '3. Liga',
        'sport': 'Football',
        'country': 'Germany',
        "numberOfTeams": 20,
        'table': 'https://www.flashscore.co.uk/football/germany/3-liga/#/U7onbg66/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/germany/3-liga/fixtures/',
    },
    'Serie A': {
        'name': 'Serie A',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-a/standings/#/6PWwAsA7/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-a/fixtures/',
    },
    'Serie B': {
        'name': 'Serie B',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-b/standings/#/jwYYXp2E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-b/fixtures/',
    },
    'Serie CA': {
        'name': 'Serie C Group A',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-c-group-a/standings/#/p4HJqOoK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-c-group-a/fixtures/',
    },
    'Serie CB': {
        'name': 'Serie C Group B',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-c-group-b/standings/#/Uygjv29s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-c-group-b/fixtures/',
    },
    'Serie CC': {
        'name': 'Serie C Group C',
        'sport': 'Football',
        'country': 'Italy',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/italy/serie-c-group-c/standings/#/6LU5xtvf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/italy/serie-c-group-c/fixtures/',
    },
    'Premiership': {
        'name': 'Premiership',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/scotland/premiership/standings/#/r9r0HS9r/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/premiership/fixtures/',
    },
    'SC Championship': {
        'name': 'SC Championship',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/scotland/championship/standings/#/xtu5Z14n/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/championship/fixtures/',
    },
    'SC League One': {
        'name': 'SC League One',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/scotland/league-one/standings/#/dtCpJFuT/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/league-one/fixtures/',
    },
    'SC League Two': {
        'name': 'SC League Two',
        'sport': 'Football',
        'country': 'Scotland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/scotland/league-two/standings/#/Cx4Bycec/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/scotland/league-two/fixtures/',
    },
    'LaLiga': {
        'name': 'LaLiga',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/spain/laliga/standings/#/vcm2MhGk/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/laliga/fixtures/',
    },
    'LaLiga2': {
        'name': 'LaLiga2',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 22,
        'table': 'https://www.flashscore.co.uk/football/spain/laliga2/standings/#/zPtBKWp2/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/laliga2/fixtures/',
    },
    'Primera RFEF 1': {
        'name': 'Primera RFEF Group 1',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/spain/primera-rfef-group-1/standings/#/W6WzKfZ2/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/primera-rfef-group-1/fixtures/',
    },
    'Primera RFEF 2': {
        'name': 'Primera RFEF Group 2',
        'sport': 'Football',
        'country': 'Spain',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/spain/segunda-rfef-group-2/standings/#/QXgmt21t/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/spain/primera-rfef-group-2/fixtures/',
    },
    'Abissnet Superiore': {
        'name': 'Abissnet Superiore',
        'sport': 'Football',
        'country': 'Albania',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/albania/abissnet-superiore/standings/#/8ECkLGL5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/albania/abissnet-superiore/fixtures/',
    },
    'Primera Divisio': {
        'name': 'Primera Divisio',
        'sport': 'Football',
        'country': 'Andorra',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/andorra/primera-divisio/standings/#/O89LE3B5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/andorra/primera-divisio/fixtures/',
    },
    'AR Premier League': {
        'name': 'AR Premier League',
        'sport': 'Football',
        'country': 'Armenia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/armenia/premier-league/standings/#/SpCaRE0E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/armenia/premier-league/fixtures/',
    },
    'AU Bundesliga': {
        'name': 'AU Bundesliga',
        'sport': 'Football',
        'country': 'Austria',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/austria/bundesliga/standings/#/WYMxZqqg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/austria/bundesliga/fixtures/',
    },
    'AZ Premier League': {
        'name': 'AZ Premier League',
        'sport': 'Football',
        'country': 'Azerbaijan',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/azerbaijan/premier-league/standings/#/xUUBfNMH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/azerbaijan/premier-league/fixtures/',
    },
    'Vysshaya Liga': {
        'name': 'Vysshaya Liga',
        'sport': 'Football',
        'country': 'Belarus',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/belarus/vysshaya-liga/standings/#/WrCSPYgt/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/belarus/vysshaya-liga/fixtures/',
    },
    'Jupiler Pro League': {
        'name': 'Jupiler Pro League',
        'sport': 'Football',
        'country': 'Belgium',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/belgium/jupiler-pro-league/standings/#/WbIIL8v0/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/belgium/jupiler-pro-league/fixtures/',
    },
    'Challenger Pro League': {
        'name': 'Challenger Pro League',
        'sport': 'Football',
        'country': 'Belgium',
        'numberOfTeams': 17,
        'table': 'https://www.flashscore.co.uk/football/belgium/challenger-pro-league/standings/#/4lti9jCi/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/belgium/challenger-pro-league/fixtures/',
    },
    'WWIN Liga BiH': {
        'name': 'WWIN Liga BiH',
        'sport': 'Football',
        'country': 'Bosnia and Herzegovina',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/bosnia-herzegovina/wwin-liga-bih/standings/#/vwgEhNbJ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bosnia-herzegovina/wwin-liga-bih/fixtures/',
    },
    'efbet League': {
        'name': 'efbet League',
        'sport': 'Football',
        'country': 'Bulgaria',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/bulgaria/efbet-league/standings/#/ID1TwQHr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bulgaria/efbet-league/fixtures/',
    },
    'HNL': {
        'name': 'HNL',
        'sport': 'Football',
        'country': 'Croatia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/croatia/hnl/standings/#/nFfMOClK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/croatia/hnl/fixtures/',
    },
    'Cyprus League': {
        'name': 'Cyprus League',
        'sport': 'Football',
        'country': 'Cyprus',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/cyprus/cyprus-league/standings/#/63RzcQXj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cyprus/cyprus-league/fixtures/',
    },
    'Chance Liga': {
        'name': 'Chance Liga',
        'sport': 'Football',
        'country': 'Czech Republic',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/czech-republic/chance-liga/standings/#/tGIvI38l/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/czech-republic/chance-liga/fixtures/',
    },
    'Chance Narodni Liga': {
        'name': 'Chance Narodni Liga',
        'sport': 'Football',
        'country': 'Czech Republic',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/czech-republic/chnl/standings/#/AwXWHfE5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/czech-republic/chnl/fixtures/',
    },
    'Superliga': {
        'name': 'Superliga',
        'sport': 'Football',
        'country': 'Denmark',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/denmark/superliga/standings/#/d4toV4hf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/denmark/superliga/fixtures/',
    },
    'Crystalbet Erovnuli Liga': {
        'name': 'Crystalbet Erovnuli Liga',
        'sport': 'Football',
        'country': 'Georgia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/georgia/crystalbet-erovnuli-liga/standings/#/h6YjUBfe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/georgia/crystalbet-erovnuli-liga/fixtures/',
    },
    'Super League': {
        'name': 'Super League',
        'sport': 'Football',
        'country': 'Greece',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/greece/super-league/standings/#/YqOkq45l/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/greece/super-league/fixtures/',
    },
    'NB I.': {
        'name': 'NB I.',
        'sport': 'Football',
        'country': 'Hungary',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/hungary/nb-i/standings/#/MgCTUmzK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/hungary/nb-i/fixtures/',
    },
    'NB II.': {
        'name': 'NB II.',
        'sport': 'Football',
        'country': 'Hungary',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/hungary/nb-ii/standings/#/hx3aPRcs/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/hungary/nb-ii/fixtures/',
    },
    'Ligat ha\'Al': {
        'name': 'Ligat ha\'Al',
        'sport': 'Football',
        'country': 'Israel',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/israel/ligat-ha-al/standings/#/QLw5lq1D/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/israel/ligat-ha-al/fixtures/',
    },
    'BGL Ligue': {
        'name': 'BGL Ligue',
        'sport': 'Football',
        'country': 'Luxembourg',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/luxembourg/bgl-ligue/standings/#/Ymj33sDD/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/luxembourg/bgl-ligue/fixtures/',
    },
    'Prva Crnogorska Liga': {
        'name': 'Prva Crnogorska Liga',
        'sport': 'Football',
        'country': 'Montenegro',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/montenegro/prva-crnogorska-liga/standings/#/hbjLULCO/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/montenegro/prva-crnogorska-liga/fixtures/',
    },
    'Eredivisie': {
        'name': 'Eredivisie',
        'sport': 'Football',
        'country': 'Netherlands',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/netherlands/eredivisie/standings/#/dWKtjvdd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/netherlands/eredivisie/fixtures/',
    },
    'Eerste Divisie': {
        'name': 'Eerste Divisie',
        'sport': 'Football',
        'country': 'Netherlands',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/netherlands/eerste-divisie/standings/#/lfs1AamS/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/netherlands/eerste-divisie/fixtures/',
    },
    'NIFL Premiership': {
        'name': 'NIFL Premiership',
        'sport': 'Football',
        'country': 'Northern Ireland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/northern-ireland/nifl-premiership/standings/#/naztrDXQ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/northern-ireland/nifl-premiership/fixtures/',
    },
    '1.MFL': {
        'name': '1.MFL',
        'sport': 'Football',
        'country': 'North Macedonia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/north-macedonia/1-mfl/standings/#/rNmH2bUG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/north-macedonia/1-mfl/fixtures/',
    },
    'Eliteserien': {
        'name': 'Eliteserien',
        'sport': 'Football',
        'country': 'Norway',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/norway/eliteserien/standings/#/r3NUJK6F/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/norway/eliteserien/fixtures/',
    },
    'Ekstraklasa': {
        'name': 'Ekstraklasa',
        'sport': 'Football',
        'country': 'Poland',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/poland/ekstraklasa/standings/#/rgKvyuf4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/poland/ekstraklasa/fixtures/',
    },
    'PL Division 1': {
        'name': 'PL Division 1',
        'sport': 'Football',
        'country': 'Poland',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/poland/division-1/standings/#/ATgMQzHj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/poland/division-1/fixtures/',
    },
    'Liga Portugal': {
        'name': 'Liga Portugal',
        'sport': 'Football',
        'country': 'Portugal',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/portugal/liga-portugal/standings/#/IgF19YCc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/portugal/liga-portugal/fixtures/',
    },
    'Liga Portugal 2': {
        'name': 'Liga Portugal 2',
        'sport': 'Football',
        'country': 'Portugal',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/portugal/liga-portugal-2/standings/#/j7D97CsA/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/portugal/liga-portugal-2/fixtures/',
    },
    'RO Superliga': {
        'name': 'RO Superliga',
        'sport': 'Football',
        'country': 'Romania',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/romania/superliga/standings/#/02YI7tIj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/romania/superliga/fixtures/',
    },
    'RU Premier League': {
        'name': 'RU Premier League',
        'sport': 'Football',
        'country': 'Russia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/russia/premier-league/standings/#/0UC6tdRa/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/russia/premier-league/fixtures/',
    },
    'FNL': {
        'name': 'FNL',
        'sport': 'Football',
        'country': 'Russia',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/russia/fnl/standings/#/CAqspVXi/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/russia/fnl/fixtures/',
    },
    'Mozzart Bet Super Liga': {
        'name': 'Mozzart Bet Super Liga',
        'sport': 'Football',
        'country': 'Serbia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/serbia/mozzart-bet-super-liga/standings/#/WCsa8Gn4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/serbia/mozzart-bet-super-liga/fixtures/',
    },
    'Nike liga': {
        'name': 'Nike liga',
        'sport': 'Football',
        'country': 'Slovakia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/slovakia/nike-liga/standings/#/UctGaeNF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/slovakia/nike-liga/fixtures/',
    },
    'Prva liga': {
        'name': 'Prva liga',
        'sport': 'Football',
        'country': 'Slovenia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/slovenia/prva-liga/standings/#/UBHtOA4s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/slovenia/prva-liga/fixtures/',
    },
    'SU Super League': {
        'name': 'SU Super League',
        'sport': 'Football',
        'country': 'Switzerland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/switzerland/super-league/standings/#/AXcskDUh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/switzerland/super-league/fixtures/',
    },
    'Challenge League': {
        'name': 'Challenge League',
        'sport': 'Football',
        'country': 'Switzerland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/switzerland/challenge-league/standings/#/pSmAL67l/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/switzerland/challenge-league/fixtures/',
    },
    'Super Lig': {
        'name': 'Super Lig',
        'sport': 'Football',
        'country': 'Turkey',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/turkey/super-lig/standings/#/EVZfW0bc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/turkey/super-lig/fixtures/',
    },
    '1.Lig': {
        'name': '1.Lig',
        'sport': 'Football',
        'country': 'Turkey',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/turkey/1-lig/standings/#/jgd2GKdJ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/turkey/1-lig/fixtures/',
    },
    'UA Premier League': {
        'name': 'UA Premier League',
        'sport': 'Football',
        'country': 'Ukraine',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/ukraine/premier-league/standings/#/ldxRUZwe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/ukraine/premier-league/fixtures/',
    },
    'Cymru Premier': {
        'name': 'Cymru Premier',
        'sport': 'Football',
        'country': 'Wales',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/wales/cymru-premier/standings/#/fuKrWpAF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/wales/cymru-premier/fixtures/',
    },
    'AL Ligue 1': {
        'name': 'AL Ligue 1',
        'sport': 'Football',
        'country': 'Algeria',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/algeria/ligue-1/standings/#/Iylbph6E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/algeria/ligue-1/fixtures/',
    },
    'Girabola': {
        'name': 'Girabola',
        'sport': 'Football',
        'country': 'Angola',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/angola/girabola/standings/#/hYzpjRb3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/angola/girabola/fixtures/',
    },
    'ABFA Premier League': {
        'name': 'ABFA Premier League',
        'sport': 'Football',
        'country': 'Antigua and Barbuda',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/antigua-barbuda/abfa-premier-league/standings/#/tALXrzcf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/antigua-barbuda/abfa-premier-league/fixtures/',
    },
    'Division di Honor': {
        'name': 'Division di Honor',
        'sport': 'Football',
        'country': 'Aruba',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/aruba/division-di-honor/standings/#/UXdLzqqn/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/aruba/division-di-honor/fixtures/',
    },
    'A-League': {
        'name': 'A-League',
        'sport': 'Football',
        'country': 'Australia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/australia/a-league/standings/#/ADPCmMSi/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/australia/a-league/fixtures/',
    },
    'BH Premier League': {
        'name': 'BH Premier League',
        'sport': 'Football',
        'country': 'Bahrain',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/football/bahrain/premier-league/standings/#/2HZas7mf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bahrain/premier-league/fixtures/',
    },
    'BFL': {
        'name': 'BFL',
        'sport': 'Football',
        'country': 'Bangladesh',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/bangladesh/bfl/standings/#/xlLBeIP1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bangladesh/bfl/fixtures/',
    },
    'BB Premier League': {
        'name': 'BB Premier League',
        'sport': 'Football',
        'country': 'Barbados',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/barbados/premier-league/standings/#/n3QvMoUH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/barbados/premier-league/fixtures/',
    },
    'BN Ligue 1': {
        'name': 'BN Ligue 1',
        'sport': 'Football',
        'country': 'Benin',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/football/benin/ligue-1/standings/#/6Zg0OKmB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/benin/ligue-1/fixtures/',
    },
    'BD Premier League': {
        'name': 'BD Premier League',
        'sport': 'Football',
        'country': 'Bermuda',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/bermuda/premier-league/standings/#/hEGySgf3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bermuda/premier-league/fixtures/',
    },
    'Division Profesional': {
        'name': 'Division Profesional',
        'sport': 'Football',
        'country': 'Bolivia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/bolivia/division-profesional/standings/#/2LBZzj8b/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/bolivia/division-profesional/fixtures/',
    },
    'BW Premier League': {
        'name': 'BW Premier League',
        'sport': 'Football',
        'country': 'Botswana',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/botswana/premier-league/standings/#/MX4zZMOp/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/botswana/premier-league/fixtures/',
    },
    'Serie A Betano': {
        'name': 'Serie A Betano',
        'sport': 'Football',
        'country': 'Brasil',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/brazil/serie-a-betano/standings/#/Yi0LvPEj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/brazil/serie-a-betano/fixtures/',
    },
    'Serie B Superbet': {
        'name': 'Serie B Superbet',
        'sport': 'Football',
        'country': 'Brasil',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/brazil/serie-b-superbet/standings/#/vF2C38ii/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/brazil/serie-b-superbet/fixtures/',
    },
    'Serie C': {
        'name': 'Serie C',
        'sport': 'Football',
        'country': 'Brasil',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/brazil/serie-c/standings/#/I51G2S6c/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/brazil/serie-c/fixtures/',
    },
    'BF Premier League': {
        'name': 'BF Premier League',
        'sport': 'Football',
        'country': 'Burkina Faso',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/burkina-faso/premier-league/standings/#/IgTYK5Cd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/burkina-faso/premier-league/fixtures/',
    },
    'Primus League': {
        'name': 'Primus League',
        'sport': 'Football',
        'country': 'Burundi',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/burundi/primus-league/standings/#/E5vTr943/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/burundi/primus-league/fixtures/',
    },
    'CPL': {
        'name': 'CPL',
        'sport': 'Football',
        'country': 'Cambodia',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/football/cambodia/cpl/standings/#/MPKtZ42j/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cambodia/cpl/fixtures/',
    },
    'Elite One': {
        'name': 'Elite One',
        'sport': 'Football',
        'country': 'Cameroon',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/cameroon/elite-one/standings/#/rJDZtHLd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cameroon/elite-one/fixtures/',
    },
    'Canadian Premier League': {
        'name': 'Canadian Premier League',
        'sport': 'Football',
        'country': 'Canada',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/football/canada/canadian-premier-league/standings/#/pWJUXCrq/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/canada/canadian-premier-league/fixtures/',
    },
    'Campeonato Nacional': {
        'name': 'Campeonato Nacional',
        'sport': 'Football',
        'country': 'Cape Verde',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/cape-verde/campeonato-nacional/standings/#/pKTIYqZg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/cape-verde/campeonato-nacional/fixtures/',
    },
    'CH Premier Division': {
        'name': 'CH Premier Division',
        'sport': 'Football',
        'country': 'Chad',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/football/chad/premiere-division/standings/#/pU6ELQTg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/chad/premiere-division/fixtures/',
    },
    'Liga de Primera': {
        'name': 'Liga de Primera',
        'sport': 'Football',
        'country': 'Chile',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/chile/liga-de-primera/standings/#/8vt19m8m/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/chile/liga-de-primera/fixtures/',
    },
    'CH Super League': {
        'name': 'CH Super League',
        'sport': 'Football',
        'country': 'China',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/china/super-league/standings/#/YZlK9BuF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/china/super-league/fixtures/',
    },
    'Primera A': {
        'name': 'Primera A',
        'sport': 'Football',
        'country': 'Columbia',
        'numberOfTeams': 20,
        'table': 'https://www.flashscore.co.uk/football/colombia/primera-a/standings/#/8MWz6dnl/standings/',
        'fixtures': 'https://www.flashscore.co.uk/football/colombia/primera-a/fixtures/',
    },
    'CG Ligue 1': {
        'name': 'CG Ligue 1',
        'sport': 'Football',
        'country': 'Congo',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/congo/ligue-1/standings/#/nwkV5fPH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/congo/ligue-1/fixtures/',
    },
    'CGDR Ligue 1': {
        'name': 'CGDR Ligue 1',
        'sport': 'Football',
        'country': 'Congo DR',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/football/congo-dr/ligue-1/standings/#/UyBrKd6E/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/congo-dr/ligue-1/fixtures/',
    },
    'CR Primera Division': {
        'name': 'CR Primera Division',
        'sport': 'Football',
        'country': 'Costa Rica',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/football/costa-rica/primera-division/standings/#/WIEkYhg4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/football/costa-rica/primera-division/fixtures/',
    },
    "Extraliga": {
        "name": "Extraliga",
        "sport": "Ice hockey",
        "country": "Czech Republic",
        'numberOfTeams': 14,
        "table": "https://www.flashscore.co.uk/ice-hockey/czech-republic/extraliga/standings/#/K0tmQWEr/standings/overall/",
        "fixtures": "https://www.flashscore.co.uk/ice-hockey/czech-republic/extraliga/fixtures/",
    }
}

module.exports = paths;