const paths = {
    'HLA': {
        'name': 'HLA',
        'sport': 'Handball',
        'country': 'Austria',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/austria/hla/standings/#/Iu4uiKsI/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/austria/hla/fixtures/',
    },
    'WHA Women': {
        'name': 'WHA Women',
        'sport': 'Handball',
        'country': 'Austria',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/austria/wha-women/standings/#/6FTQ2cRN/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/austria/wha-women/fixtures/',
    },
    'Division 1 BLRH': {
        'name': 'Division 1',
        'sport': 'Handball',
        'country': 'Belarus',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/handball/belarus/division-1/standings/#/bwYOLqR6/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/belarus/division-1/fixtures/',
    },
    'Division 1 BLGH': {
        'name': 'Division 1',
        'sport': 'Handball',
        'country': 'Belgium',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/handball/belgium/division-1/standings/#/8KTHASCl/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/belgium/division-1/fixtures/',
    },
    'Premijer Liga': {
        'name': 'Premijer Liga',
        'sport': 'Handball',
        'country': 'Bosnia & Herzegovina',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/bosnia-herzegovina/premijer-liga/standings/#/6ZeGYMAC/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/bosnia-herzegovina/premijer-liga/fixtures/',
    },
    'A RHG': {
        'name': 'A RHG',
        'sport': 'Handball',
        'country': 'Bulgaria',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/handball/bulgaria/a-rhg/standings/#/EaaOW0uP/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/bulgaria/a-rhg/fixtures/',
    },
    '1. HRL Women': {
        'name': '1. HRL Women',
        'sport': 'Handball',
        'country': 'Croatia',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/croatia/1-hrl-women/standings/#/0zCUBWsB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/croatia/1-hrl-women/fixtures/',
    },
    'Extraliga CZEH': {
        'name': 'Extraliga',
        'sport': 'Handball',
        'country': 'Czech Republic',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/czech-republic/extraliga/standings/#/rRTOnjyn/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/czech-republic/extraliga/fixtures/',
    },
    'Herre Handbold Ligaen': {
        'name': 'Herre Handbold Ligaen',
        'sport': 'Handball',
        'country': 'Denmark',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/denmark/herre-handbold-ligaen/standings/#/x812hxJr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/denmark/herre-handbold-ligaen/fixtures/',
    },
    'Kvindeligaen Women': {
        'name': 'Kvindeligaen Women',
        'sport': 'Handball',
        'country': 'Denmark',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/denmark/kvindeligaen-women/standings/#/be5CPzfK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/denmark/kvindeligaen-women/fixtures/',
    },
    'Aktialiiga': {
        'name': 'Aktialiiga',
        'sport': 'Handball',
        'country': 'Finland',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/handball/finland/aktialiiga/standings/#/rsjHMvUj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/finland/aktialiiga/fixtures/',
    },
    'Starligue': {
        'name': 'Starligue',
        'sport': 'Handball',
        'country': 'France',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/handball/france/starligue/standings/#/neCDnec2/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/france/starligue/fixtures/',
    },
    'Proligue': {
        'name': 'Proligue',
        'sport': 'Handball',
        'country': 'France',
        'numberOfTeams': 15,
        'table': 'https://www.flashscore.co.uk/handball/france/proligue/standings/#/dneog7G8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/france/proligue/fixtures/',
    },
    'Bundesliga GERH': {
        'name': 'Bundesliga',
        'sport': 'Handball',
        'country': 'Germany',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/handball/germany/bundesliga/standings/#/Wde0DvMa/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/germany/bundesliga/fixtures/',
    },
    '2. Bundesliga': {
        'name': '2. Bundesliga',
        'sport': 'Handball',
        'country': 'Germany',
        'numberOfTeams': 18,
        'table': 'https://www.flashscore.co.uk/handball/germany/2-bundesliga/standings/#/hCq9BIjC/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/germany/2-bundesliga/fixtures/',
    },
    '1. Bundesliga Women GERH': {
        'name': '1. Bundesliga Women',
        'sport': 'Handball',
        'country': 'Germany',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/handball/germany/1-bundesliga-women/standings/#/GYvrSwyg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/germany/1-bundesliga-women/fixtures/',
    },
    'A1 GREH': {
        'name': 'A1',
        'sport': 'Handball',
        'country': 'Greece',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/greece/a1/standings/#/IcJKANu1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/greece/a1/fixtures/',
    },
    'NB I HUNB': {
        'name': 'NB I',
        'sport': 'Handball',
        'country': 'Hungary',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/hungary/nb-i/standings/#/zVXNal1k/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/hungary/nb-i/fixtures/',
    },
    'NB I Women': {
        'name': 'NB I Women',
        'sport': 'Handball',
        'country': 'Hungary',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/hungary/nb-i-women/standings/#/zZuZJ9hL/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/hungary/nb-i-women/fixtures/',
    },
    'Olis Deildin': {
        'name': 'Olis Deildin',
        'sport': 'Handball',
        'country': 'Iceland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/iceland/olis-deildin/standings/#/6msV9ACN/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/iceland/olis-deildin/fixtures/',
    },
    'Olis Deild Women': {
        'name': 'Olis Deild Women',
        'sport': 'Handball',
        'country': 'Iceland',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/handball/iceland/olis-deild-women/standings/#/MqZeSiSi/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/iceland/olis-deild-women/fixtures/',
    },
    'Division 1 ISRH': {
        'name': 'Division 1',
        'sport': 'Handball',
        'country': 'Israel',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/handball/israel/division-1/standings/#/fy8TWwAl/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/israel/division-1/fixtures/',
    },
    'Serie A ITAH': {
        'name': 'Serie A',
        'sport': 'Handball',
        'country': 'Italy',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/italy/serie-a/standings/#/hlN7N9RG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/italy/serie-a/fixtures/',
    },
    'Serie A Women': {
        'name': 'Serie A Women',
        'sport': 'Handball',
        'country': 'Italy',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/italy/serie-a-women/standings/#/QXiVJ0Qr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/italy/serie-a-women/fixtures/',
    },
    'League H': {
        'name': 'League H',
        'sport': 'Handball',
        'country': 'Japan',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/japan/league-h/standings/#/AcZSseO6/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/japan/league-h/fixtures/',
    },
    'League H Women': {
        'name': 'League H Women',
        'sport': 'Handball',
        'country': 'Japan',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/handball/japan/league-h-women/standings/#/zLrW3xoQ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/japan/league-h-women/fixtures/',
    },
    'AXA League': {
        'name': 'AXA League',
        'sport': 'Handball',
        'country': 'Luxembourg',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/handball/luxembourg/axa-league/standings/#/St6Ypknd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/luxembourg/axa-league/fixtures/',
    },
    'Prva liga MNGH': {
        'name': 'Prva liga',
        'sport': 'Handball',
        'country': 'Montenegro',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/handball/montenegro/prva-liga/standings/#/G6hnZjMh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/montenegro/prva-liga/fixtures/',
    },
    'Eredivisie NETH': {
        'name': 'Eredivisie',
        'sport': 'Handball',
        'country': 'Netherlands',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/netherlands/eredivisie/standings/#/rPMYvHKb/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/netherlands/eredivisie/fixtures/',
    },
    'Eredivisie Women NETH': {
        'name': 'Eredivisie Women',
        'sport': 'Handball',
        'country': 'Netherlands',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/netherlands/eredivisie-women/standings/#/hMSJp32e/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/netherlands/eredivisie-women/fixtures/',
    },
    'Superleague NMCH': {
        'name': 'Superleague',
        'sport': 'Handball',
        'country': 'North Macedonia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/north-macedonia/superleague/standings/#/2FCpTe1n/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/north-macedonia/superleague/fixtures/',
    },
    'REMA 1000-ligaen': {
        'name': 'REMA 1000-ligaen',
        'sport': 'Handball',
        'country': 'Norway',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/norway/rema-1000-ligaen/standings/#/nZEWC1Ws/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/norway/rema-1000-ligaen/fixtures/',
    },
    'REMA 1000-ligaen women': {
        'name': 'REMA 1000-ligaen women',
        'sport': 'Handball',
        'country': 'Norway',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/norway/rema-1000-ligaen-women/standings/#/hbr37c0J/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/norway/rema-1000-ligaen-women/fixtures/',
    },
    'Superliga POLH': {
        'name': 'Superliga',
        'sport': 'Handball',
        'country': 'Poland',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/handball/poland/superliga/standings/#/W0ZHOndt/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/poland/superliga/fixtures/',
    },
    'Superliga Women': {
        'name': 'Superliga Women',
        'sport': 'Handball',
        'country': 'Poland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/handball/poland/superliga-women/standings/#/OQG0CDgd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/poland/superliga-women/fixtures/',
    },
    'Andebol 1': {
        'name': 'Andebol 1',
        'sport': 'Handball',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/portugal/andebol-1/standings/#/KEZlvjhe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/portugal/andebol-1/fixtures/',
    },
    '1a Divisao Women': {
        'name': '1a Divisao Women',
        'sport': 'Handball',
        'country': 'Portugal',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/handball/portugal/1a-divisao-women/standings/#/MoGmk76D/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/portugal/1a-divisao-women/fixtures/',
    },
    'Liga Nationala': {
        'name': 'Liga Nationala',
        'sport': 'Handball',
        'country': 'Romania',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/handball/romania/liga-nationala/standings/#/Aeju35nl/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/romania/liga-nationala/fixtures/',
    },
    'Liga Nationala Women': {
        'name': 'Liga Nationala Women',
        'sport': 'Handball',
        'country': 'Romania',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/romania/liga-nationala-women/standings/#/vkceaNoD/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/romania/liga-nationala-women/fixtures/',
    },
    'Superleague RUSH': {
        'name': 'Superleague',
        'sport': 'Handball',
        'country': 'Russia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/russia/superleague/standings/#/0t3krs0t/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/russia/superleague/fixtures/',
    },
    'Superleague Women RUSH': {
        'name': 'Superleague Women',
        'sport': 'Handball',
        'country': 'Russia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/russia/superleague-women/standings/#/GpZCixqB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/russia/superleague-women/fixtures/',
    },
    'ARKUS Liga': {
        'name': 'ARKUS Liga',
        'sport': 'Handball',
        'country': 'Serbia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/serbia/arkus-liga/standings/#/CQo91SUP/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/serbia/arkus-liga/fixtures/',
    },
    'ARKUS Liga Women': {
        'name': 'ARKUS Liga Women',
        'sport': 'Handball',
        'country': 'Serbia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/serbia/arkus-liga-women/standings/#/xMtDj2MO/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/serbia/arkus-liga-women/fixtures/',
    },
    '1. NLB Liga': {
        'name': '1. NLB Liga',
        'sport': 'Handball',
        'country': 'Slovenia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/slovenia/1-nlb-lig/standings/#/GSHIlbu3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/slovenia/1-nlb-lig/fixtures/',
    },
    '1. SRL Women': {
        'name': '1. SRL Women',
        'sport': 'Handball',
        'country': 'Slovenia',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/handball/slovenia/1-srl-women/standings/#/fqnidCP7/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/slovenia/1-srl-women/fixtures/',
    },
    'H League Women': {
        'name': 'H League Women',
        'sport': 'Handball',
        'country': 'South Korea',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/handball/south-korea/h-league-women/standings/#/bk2axQio/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/south-korea/h-league-women/fixtures/',
    },
    'Liga ASOBAL': {
        'name': 'Liga ASOBAL',
        'sport': 'Handball',
        'country': 'Spain',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/handball/spain/liga-asobal/standings/#/8EOt6N65/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/spain/liga-asobal/fixtures/',
    },
    'Division de Honor Women': {
        'name': 'Division de Honor Women',
        'sport': 'Handball',
        'country': 'Spain',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/spain/division-de-honor-women/standings/#/KtjFXa54/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/spain/division-de-honor-women/fixtures/',
    },
    'Handbollsligan': {
        'name': 'Handbollsligan',
        'sport': 'Handball',
        'country': 'Sweden',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/handball/sweden/handbollsligan/standings/#/b7u2Q83e/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/sweden/handbollsligan/fixtures/',
    },
    'Handbollsligan Women': {
        'name': 'Handbollsligan Women',
        'sport': 'Handball',
        'country': 'Sweden',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/handball/sweden/handbollsligan-women/standings/#/IN6JxGbs/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/sweden/handbollsligan-women/fixtures/',
    },
    'NLA SUIH': {
        'name': 'NLA',
        'sport': 'Handball',
        'country': 'Switzerland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/handball/switzerland/nla/standings/#/ANxpXBSI/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/switzerland/nla/fixtures/',
    },
    'Superlig': {
        'name': 'Superlig',
        'sport': 'Handball',
        'country': 'Turkey',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/handball/turkey/superlig/standings/#/xYW82NX9/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/turkey/superlig/fixtures/',
    },
    'Superleague UKRH': {
        'name': 'Superleague',
        'sport': 'Handball',
        'country': 'Ukraine',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/handball/ukraine/superleague/standings/#/MZk3CvnS/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/handball/ukraine/superleague/fixtures/',
    },


};

module.exports = paths;