const paths = {
    'Premier League BLRF': {
        'name': 'Premier League',
        'sport': 'Futsal',
        'country': 'Belarus',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/futsal/belarus/premier-league/standings/#/EuDjuKX1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/belarus/premier-league/fixtures/',
    },
    'Division 1 BLGF': {
        'name': 'Division 1',
        'sport': 'Futsal',
        'country': 'Belgium',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/futsal/belgium/division-1/standings/#/r5h3lX4b/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/belgium/division-1/fixtures/',
    },
    'LNF': {
        'name': 'LNF',
        'sport': 'Futsal',
        'country': 'Brazil',
        'numberOfTeams': 24,
        'table': 'https://www.flashscore.co.uk/futsal/brazil/lnf/standings/#/EVqDnhPc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/brazil/lnf/fixtures/',
    },
    'HMNL': {
        'name': 'HMNL',
        'sport': 'Futsal',
        'country': 'Croatia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/futsal/croatia/hmnl/standings/#/Or0RCMU6/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/croatia/hmnl/fixtures/',
    },
    '1. Futsal liga': {
        'name': '1. Futsal liga',
        'sport': 'Futsal',
        'country': 'Czech Republic',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/futsal/czech-republic/1-futsal-liga/standings/#/AeW12dc5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/czech-republic/1-futsal-liga/fixtures/',
    },
    'Futsal Ligaen': {
        'name': 'Futsal Ligaen',
        'sport': 'Futsal',
        'country': 'Denmark',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/futsal/denmark/futsal-ligaen/standings/#/6Dt7YKw1/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/denmark/futsal-ligaen/fixtures/',
    },
    'Saaliliiga': {
        'name': 'Saaliliiga',
        'sport': 'Futsal',
        'country': 'Estonia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/futsal/estonia/saaliliiga/standings/#/GKZWezgM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/estonia/saaliliiga/fixtures/',
    },
    'Liiga FINF': {
        'name': 'Liiga',
        'sport': 'Futsal',
        'country': 'Finland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/finland/liiga/standings/#/KpADVtzg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/finland/liiga/fixtures/',
    },
    'Liiga Women': {
        'name': 'Liiga Women',
        'sport': 'Futsal',
        'country': 'Finland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/finland/liiga-women/standings/#/AJ20E8E7/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/finland/liiga-women/fixtures/',
    },
    'D1': {
        'name': 'D1',
        'sport': 'Futsal',
        'country': 'France',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/futsal/france/d1/standings/#/beewQx4U/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/france/d1/fixtures/',
    },
    'Futsal League': {
        'name': 'Futsal League',
        'sport': 'Futsal',
        'country': 'Georgia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/futsal/georgia/futsal-league/standings/#/YPeK15Gl/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/georgia/futsal-league/fixtures/',
    },
    'Bundesliga GERF': {
        'name': 'Bundesliga',
        'sport': 'Futsal',
        'country': 'Germany',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/futsal/germany/bundesliga/standings/#/O8mQvFmm/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/germany/bundesliga/fixtures/',
    },
    'Super League GREF': {
        'name': 'Super League',
        'sport': 'Futsal',
        'country': 'Greece',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/greece/super-league/standings/#/Ekx9FYwI/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/greece/super-league/fixtures/',
    },
    'NB I': {
        'name': 'NB I',
        'sport': 'Futsal',
        'country': 'Hungary',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/hungary/nb-i/standings/#/A55MOsth/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/hungary/nb-i/fixtures/',
    },
    'Pro Futsal League': {
        'name': 'Pro Futsal League',
        'sport': 'Futsal',
        'country': 'Indonesia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/indonesia/pro-futsal-league/standings/#/KGCM98uC/standings/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/indonesia/pro-futsal-league/fixtures/',
    },
    'Serie A ITAF': {
        'name': 'Serie A',
        'sport': 'Futsal',
        'country': 'Italy',
        'numberOfTeams': 15,
        'table': 'https://www.flashscore.co.uk/futsal/italy/serie-a/standings/#/UZgMUF7k/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/italy/serie-a/fixtures/',
    },
    'F.League': {
        'name': 'F.League',
        'sport': 'Futsal',
        'country': 'Japan',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/japan/f-league/standings/#/SA1XlyaL/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/japan/f-league/fixtures/',
    },
    'Championship KAZF': {
        'name': 'Championship',
        'sport': 'Futsal',
        'country': 'Kazakhstan',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/kazakhstan/championship/standings/#/G49N3zEE/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/kazakhstan/championship/fixtures/',
    },
    'Optibet Virsliga': {
        'name': 'Optibet Virsliga',
        'sport': 'Futsal',
        'country': 'Latvia',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/futsal/latvia/optibet-virsliga/standings/#/dIg2dh6l/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/latvia/optibet-virsliga/fixtures/',
    },
    'Eredivisie NETF': {
        'name': 'Eredivisie',
        'sport': 'Futsal',
        'country': 'Netherlands',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/futsal/netherlands/eredivisie/standings/#/OdotlAWH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/netherlands/eredivisie/fixtures/',
    },
    'Ekstraklasa POLF': {
        'name': 'Ekstraklasa',
        'sport': 'Futsal',
        'country': 'Poland',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/futsal/poland/ekstraklasa/standings/#/lbZiGa6L/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/poland/ekstraklasa/fixtures/',
    },
    'Liga Placard': {
        'name': 'Liga Placard',
        'sport': 'Futsal',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/portugal/liga-placard/standings/#/Ek2mqpRd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/portugal/liga-placard/fixtures/',
    },
    'Liga Placard Women': {
        'name': 'Liga Placard Women',
        'sport': 'Futsal',
        'country': 'Portugal',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/futsal/portugal/liga-placard-women/standings/#/84BzmdlK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/portugal/liga-placard-women/fixtures/',
    },
    'Liga I': {
        'name': 'Liga I',
        'sport': 'Futsal',
        'country': 'Romania',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/futsal/romania/liga-i/standings/#/KSnzD8R8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/romania/liga-i/fixtures/',
    },
    'SuperLiga': {
        'name': 'SuperLiga',
        'sport': 'Futsal',
        'country': 'Russia',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/futsal/russia/superliga/standings/#/thMqJGvg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/russia/superliga/fixtures/',
    },
    'Extraliga CZEF': {
        'name': 'Extraliga',
        'sport': 'Futsal',
        'country': 'Slovakia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/futsal/slovakia/extraliga/standings/#/zqXsWgOb/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/slovakia/extraliga/fixtures/',
    },
    '1. SFL': {
        'name': '1. SFL',
        'sport': 'Futsal',
        'country': 'Slovenia',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/futsal/slovenia/1-sfl/standings/#/xC5VMkoo/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/slovenia/1-sfl/fixtures/',
    },
    'Liga Nacional': {
        'name': 'Liga Nacional',
        'sport': 'Futsal',
        'country': 'Spain',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/futsal/spain/liga-nacional/standings/#/Ma1Dw2yq/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/spain/liga-nacional/fixtures/',
    },
    'Primera Division Women': {
        'name': 'Primera Division Women',
        'sport': 'Futsal',
        'country': 'Spain',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/futsal/spain/primera-division-women/standings/#/0f4OcNSE/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/spain/primera-division-women/fixtures/',
    },
    'Futsalligan': {
        'name': 'Futsalligan',
        'sport': 'Futsal',
        'country': 'Sweden',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/sweden/futsalligan/standings/#/lzD1eMEO/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/sweden/futsalligan/fixtures/',
    },
    'Premier League': {
        'name': 'Premier League',
        'sport': 'Futsal',
        'country': 'Switzerland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/futsal/switzerland/premier-league/standings/#/UXERD3Uh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/switzerland/premier-league/fixtures/',
    },
    'Extra-Liga': {
        'name': 'Extra-Liga',
        'sport': 'Futsal',
        'country': 'Ukraine',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/futsal/ukraine/extra-liga/standings/#/QR2JFG5c/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/futsal/ukraine/extra-liga/fixtures/',
    },

};

module.exports = paths;