const paths = {
    'Liga Women': {
        'name': 'Liga Women',
        'sport': 'Volleyball',
        'country': 'Argentina',
        'numberOfTeams': 15,
        'table': 'https://www.flashscore.co.uk/volleyball/argentina/liga-women/standings/#/xlBMu8Am/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/argentina/liga-women/fixtures/',
    },
    'AVL': {
        'name': 'AVL',
        'sport': 'Volleyball',
        'country': 'Austria',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/austria/avl/standings/#/p4DzSTB4/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/austria/avl/fixtures/',
    },
    'Division A': {
        'name': 'Division A',
        'sport': 'Volleyball',
        'country': 'Belarus',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/belarus/division-a/standings/#/KMmCsYAc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belarus/division-a/fixtures/',
    },
    'Championship Women': {
        'name': 'Championship Women',
        'sport': 'Volleyball',
        'country': 'Belarus',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/belarus/championship-women/standings/#/rDKdby7C/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belarus/championship-women/fixtures/',
    },
    'Volley League': {
        'name': 'Volley League',
        'sport': 'Volleyball',
        'country': 'Belgium',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league/standings/#/ATVv7dW0/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league/fixtures/',
    },
    'Volley League Women': {
        'name': 'Volley League Women',
        'sport': 'Volleyball',
        'country': 'Belgium',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league-women/standings/#/dET3kS7r/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/belgium/volley-league-women/fixtures/',
    },
    'Premijer liga': {
        'name': 'Premijer liga',
        'sport': 'Volleyball',
        'country': 'Bosnia & Herzegovina',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/bosnia-herzegovina/premijer-liga/standings/#/8AE7aIgc/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/bosnia-herzegovina/premijer-liga/fixtures/',
    },
    'SuperLiga BRV': {
        'name': 'SuperLiga',
        'sport': 'Volleyball',
        'country': 'Brazil',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/brazil/superliga/standings/#/vs3g3i0k/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/brazil/superliga/fixtures/',
    },
    'Superliga - Women BRV': {
        'name': 'Superliga - Women',
        'sport': 'Volleyball',
        'country': 'Brazil',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/brazil/superliga-women/standings/#/SzBqIjFr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/brazil/superliga-women/fixtures/',
    },
    'SuperLiga BGV': {
        'name': 'SuperLiga',
        'sport': 'Volleyball',
        'country': 'Bulgaria',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga/standings/#/fqERiF2T/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga/fixtures/',
    },
    'Superliga - Women BGV': {
        'name': 'Superliga - Women',
        'sport': 'Volleyball',
        'country': 'Bulgaria',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga-women/standings/#/EZicDjtm/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/bulgaria/superliga/fixtures/',
    },
    'Superliga CRV': {
        'name': 'Superliga',
        'sport': 'Volleyball',
        'country': 'Croatia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/croatia/superliga/standings/#/SOGtAwfB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/croatia/superliga/fixtures/',
    },
    'Superliga Women CRV': {
        'name': 'Superliga Women',
        'sport': 'Volleyball',
        'country': 'Croatia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/croatia/superliga-women/standings/#/ImQBFPy8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/croatia/superliga-women/fixtures/',
    },
    'Extraliga': {
        'name': 'Extraliga',
        'sport': 'Volleyball',
        'country': 'Czech Republic',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga/standings/#/reiEGDcK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga/fixtures/',
    },
    'Extraliga Women': {
        'name': 'Extraliga Women',
        'sport': 'Volleyball',
        'country': 'Czech Republic',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga-women/standings/#/8jnI5mkJ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/czech-republic/extraliga-women/fixtures/',
    },
    'Volleyligaen': {
        'name': 'Volleyligaen',
        'sport': 'Volleyball',
        'country': 'Denmark',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen/standings/#/zXUcuk7T/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen/fixtures/',
    },
    'Volleyligaen Women': {
        'name': 'Volleyligaen Women',
        'sport': 'Volleyball',
        'country': 'Denmark',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen-women/standings/#/2wqzNa3F/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/denmark/volleyligaen-women/fixtures/',
    },
    'Super League': {
        'name': 'Super League',
        'sport': 'Volleyball',
        'country': 'England',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/england/super-league/standings/#/dMgYfg9s/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/england/super-league/fixtures/',
    },
    'Super League Women': {
        'name': 'Super League Women',
        'sport': 'Volleyball',
        'country': 'England',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/england/super-league-women/standings/#/6yZm4ubT/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/england/super-league-women/fixtures/',
    },
    'Meistriliiga Women': {
        'name': 'Meistriliiga Women',
        'sport': 'Volleyball',
        'country': 'Estonia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/estonia/meistriliiga-women/standings/#/W8yGbIVb/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/estonia/meistriliiga-women/fixtures/',
    },
    'Mestaruusliiga': {
        'name': 'Mestaruusliiga',
        'sport': 'Volleyball',
        'country': 'Finland',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga/standings/#/QPLQ6DET/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga/fixtures/',
    },
    'Mestaruusliiga Women': {
        'name': 'Mestaruusliiga Women',
        'sport': 'Volleyball',
        'country': 'Finland',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga-women/standings/#/xWom5a46/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/finland/mestaruusliiga-women/fixtures/',
    },
    'Ligue A': {
        'name': 'Ligue A',
        'sport': 'Volleyball',
        'country': 'France',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/france/ligue-a/standings/#/WzjcpSNF/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/france/ligue-a/fixtures/',
    },
    'Ligue A Women': {
        'name': 'Ligue A Women',
        'sport': 'Volleyball',
        'country': 'France',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/volleyball/france/ligue-a-women/standings/#/dj77DxFG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/france/ligue-a-women/fixtures/',
    },
    '1. Bundesliga': {
        'name': '1. Bundesliga',
        'sport': 'Volleyball',
        'country': 'Germany',
        'numberOfTeams': 15,
        'table': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga/standings/#/4xxUGybK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga/fixtures/',
    },
    '1. Bundesliga Women': {
        'name': '1. Bundesliga Women',
        'sport': 'Volleyball',
        'country': 'Germany',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga-women/standings/#/4KlnFuYj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/germany/1-bundesliga-women/fixtures/',
    },
    'A1': {
        'name': 'A1',
        'sport': 'Volleyball',
        'country': 'Greece',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/greece/a1/standings/#/2Zh74n2n/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/greece/a1/fixtures/',
    },
    'A1 Women': {
        'name': 'A1 Women',
        'sport': 'Volleyball',
        'country': 'Greece',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/greece/a1-women/standings/#/Ia4zHp3k/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/greece/a1-women/fixtures/',
    },
    'Extraliga HUV': {
        'name': 'Extraliga',
        'sport': 'Volleyball',
        'country': 'Hungary',
        'numberOfTeams': 13,
        'table': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga/standings/#/x6A4QiQh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga/fixtures/',
    },
    'Extraliga Women HUV': {
        'name': 'Extraliga Women',
        'sport': 'Volleyball',
        'country': 'Hungary',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga-women/standings/#/0pBq578c/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/hungary/extraliga-women/fixtures/',
    },
    'Mizunodeild': {
        'name': 'Mizunodeild',
        'sport': 'Volleyball',
        'country': 'Iceland',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/iceland/mizunodeild/standings/#/CIRSZNc3/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/iceland/mizunodeild/fixtures/',
    },
    'Prime Volleyball': {
        'name': 'Prime Volleyball',
        'sport': 'Volleyball',
        'country': 'India',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/india/prime-volleyball/standings/#/4YN1VJgo/standings/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/india/prime-volleyball/fixtures/',
    },
    'Super League IRNV': {
        'name': 'Super League',
        'sport': 'Volleyball',
        'country': 'Iran',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/iran/super-league/standings/#/f3IwLXxg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/iran/super-league/fixtures/',
    },
    'Premier League ISRV': {
        'name': 'Premier League',
        'sport': 'Volleyball',
        'country': 'Israel',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/israel/premier-league/standings/#/KSzZNlqK/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/israel/premier-league/fixtures/',
    },
    'SuperLega': {
        'name': 'SuperLega',
        'sport': 'Volleyball',
        'country': 'Italy',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/italy/superlega/standings/#/CMyd5b1D/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/italy/superlega/fixtures/',
    },
    'Serie A1 Women': {
        'name': 'Serie A1 Women',
        'sport': 'Volleyball',
        'country': 'Italy',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/italy/serie-a1-women/standings/#/lIDDcDbB/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/italy/serie-a1-women/fixtures/',
    },
    'SV.League': {
        'name': 'SV.League',
        'sport': 'Volleyball',
        'country': 'Japan',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/japan/sv-league/standings/#/GEYn8FZp/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/japan/sv-league/fixtures/',
    },
    'SV.League Women': {
        'name': 'SV.League Women',
        'sport': 'Volleyball',
        'country': 'Japan',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/japan/sv-league-women/standings/#/nRncuEAM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/japan/sv-league-women/fixtures/',
    },
    'National League': {
        'name': 'National League',
        'sport': 'Volleyball',
        'country': 'Kazakhstan',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league/standings/#/fPLyMNGG/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league/fixtures/',
    },
    'National League Women': {
        'name': 'National League Women',
        'sport': 'Volleyball',
        'country': 'Kazakhstan',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league-women/standings/#/fVQaGhpe/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/kazakhstan/national-league-women/fixtures/',
    },
    '1st Division': {
        'name': '1st Division',
        'sport': 'Volleyball',
        'country': 'Lebanon',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/lebanon/1st-division/standings/#/hvC6nHQj/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/lebanon/1st-division/fixtures/',
    },
    'Superliga Women MNTV': {
        'name': 'Superliga Women',
        'sport': 'Volleyball',
        'country': 'Montenegro',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/montenegro/superliga-women/standings/#/SxnWFGhd/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/montenegro/superliga-women/fixtures/',
    },
    'Eredivisie': {
        'name': 'Eredivisie',
        'sport': 'Volleyball',
        'country': 'Netherlands',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie/standings/#/Kt8MdPYQ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie/fixtures/',
    },
    'Eredivisie Women': {
        'name': 'Eredivisie Women',
        'sport': 'Volleyball',
        'country': 'Netherlands',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie-women/standings/#/6mgN4gHb/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/netherlands/eredivisie-women/fixtures/',
    },
    'Eliteserien': {
        'name': 'Eliteserien',
        'sport': 'Volleyball',
        'country': 'Norway',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien/standings/#/Oj0KU9pA/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien/fixtures/',
    },
    'Eliteserien Women': {
        'name': 'Eliteserien Women',
        'sport': 'Volleyball',
        'country': 'Norway',
        'numberOfTeams': 9,
        'table': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien-women/standings/#/UwQ7LdDD/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/norway/eliteserien-women/fixtures/',
    },
    'LNSV': {
        'name': 'LNSV',
        'sport': 'Volleyball',
        'country': 'Peru',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/peru/lnsv/standings/#/8IAmewkQ/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/peru/lnsv/fixtures/',
    },
    'LNSV Women': {
        'name': 'LNSV Women',
        'sport': 'Volleyball',
        'country': 'Peru',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/peru/lnsv-women/standings/#/MLEvqLMH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/peru/lnsv-women/fixtures/',
    },
    'PlusLiga': {
        'name': 'PlusLiga',
        'sport': 'Volleyball',
        'country': 'Poland',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/poland/plusliga/standings/#/zD2V5lKr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/poland/plusliga/fixtures/',
    },
    'TAURON Liga Women': {
        'name': 'TAURON Liga Women',
        'sport': 'Volleyball',
        'country': 'Poland',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/poland/tauron-liga-women/standings/#/IqOgnHwh/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/poland/tauron-liga-women/fixtures/',
    },
    'Campeonato Nacional': {
        'name': 'Campeonato Nacional',
        'sport': 'Volleyball',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/portugal/campeonato-nacional/standings/#/WWcvOKJP/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/portugal/campeonato-nacional/fixtures/',
    },
    '1. Divisao Women': {
        'name': '1. Divisao Women',
        'sport': 'Volleyball',
        'country': 'Portugal',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/portugal/1-divisao-women/standings/#/zsjxd5V8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/portugal/1-divisao-women/fixtures/',
    },
    'Volleyball League': {
        'name': 'Volleyball League',
        'sport': 'Volleyball',
        'country': 'Qatar',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/qatar/volleyball-league/standings/#/lARRDSXo/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/qatar/volleyball-league/fixtures/',
    },
    'Divizia A1': {
        'name': 'Divizia A1',
        'sport': 'Volleyball',
        'country': 'Romania',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1/standings/#/CfZPZRwC/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1/fixtures/',
    },
    'Divizia A1 Women': {
        'name': 'Divizia A1 Women',
        'sport': 'Volleyball',
        'country': 'Romania',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1-women/standings/#/IRGbjvU9/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/romania/divizia-a1-women/fixtures/',
    },
    'Super League RUSV': {
        'name': 'Super League',
        'sport': 'Volleyball',
        'country': 'Russia',
        'numberOfTeams': 16,
        'table': 'https://www.flashscore.co.uk/volleyball/russia/super-league/standings/#/fRflGfcL/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/russia/super-league/fixtures/',
    },
    'Super League - Women RUSV': {
        'name': 'Super League - Women',
        'sport': 'Volleyball',
        'country': 'Russia',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/russia/super-league-women/standings/#/88irGk05/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/russia/super-league-women/fixtures/',
    },
    'Superliga SRBV': {
        'name': 'Superliga',
        'sport': 'Volleyball',
        'country': 'Serbia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/serbia/superliga/standings/#/f3jJ5jX8/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/serbia/superliga/fixtures/',
    },
    'Superliga Women SRBV': {
        'name': 'Superliga Women',
        'sport': 'Volleyball',
        'country': 'Serbia',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/serbia/superliga-women/standings/#/E7iqAxF5/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/serbia/superliga-women/fixtures/',
    },
    'Extraliga SVKV': {
        'name': 'Extraliga',
        'sport': 'Volleyball',
        'country': 'Slovakia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga/standings/#/6uF0pzwg/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga/fixtures/',
    },
    'Extraliga Women SVKV': {
        'name': 'Extraliga Women',
        'sport': 'Volleyball',
        'country': 'Slovakia',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga-women/standings/#/2w1O3LZr/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/slovakia/extraliga-women/fixtures/',
    },
    '1. DOL': {
        'name': '1. DOL',
        'sport': 'Volleyball',
        'country': 'Slovenia',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/slovenia/1-dol/standings/#/zmTR92TI/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/slovenia/1-dol/fixtures/',
    },
    'SuperLiga SPAV': {
        'name': 'SuperLiga',
        'sport': 'Volleyball',
        'country': 'Spain',
        'numberOfTeams': 12,
        'table': 'https://www.flashscore.co.uk/volleyball/spain/superliga/standings/#/WAbtzgrH/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/spain/superliga/fixtures/',
    },
    'Elitserien': {
        'name': 'Elitserien',
        'sport': 'Volleyball',
        'country': 'Sweden',
        'numberOfTeams': 11,
        'table': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien/standings/#/SrklaUSP/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien/fixtures/',
    },
    'Elitserien Women': {
        'name': 'Elitserien Women',
        'sport': 'Volleyball',
        'country': 'Sweden',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien-women/standings/#/QwoE3GAM/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/sweden/elitserien-women/fixtures/',
    },
    'NLA': {
        'name': 'NLA',
        'sport': 'Volleyball',
        'country': 'Switzerland',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/switzerland/nla/standings/#/65KZNA1e/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/switzerland/nla/fixtures/',
    },
    'NLA Women': {
        'name': 'NLA Women',
        'sport': 'Volleyball',
        'country': 'Switzerland',
        'numberOfTeams': 10,
        'table': 'https://www.flashscore.co.uk/volleyball/switzerland/nla-women/standings/#/WCZSXILU/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/switzerland/nla-women/fixtures/',
    },
    'Efeler Ligi': {
        'name': 'Efeler Ligi',
        'sport': 'Volleyball',
        'country': 'Turkey',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/turkey/efeler-ligi/standings/#/K82wvr9j/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/turkey/efeler-ligi/fixtures/',
    },
    'Sultanlar Ligi Women': {
        'name': 'Sultanlar Ligi Women',
        'sport': 'Volleyball',
        'country': 'Turkey',
        'numberOfTeams': 14,
        'table': 'https://www.flashscore.co.uk/volleyball/turkey/sultanlar-ligi-women/standings/#/2Hab6Xrf/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/turkey/sultanlar-ligi-women/fixtures/',
    },
    'Superleague UKRV': {
        'name': 'Superleague',
        'sport': 'Volleyball',
        'country': 'Ukraine',
        'numberOfTeams': 8,
        'table': 'https://www.flashscore.co.uk/volleyball/ukraine/superleague/standings/#/23OXsI1S/standings/overall/',
        'fixtures': 'https://www.flashscore.co.uk/volleyball/ukraine/superleague/fixtures/',
    },

}

module.exports = paths;